<div id="app" class="app">

    <div class="login login-with-news-feed">

        <div class="news-feed">
            <div class="news-image" style="background-image: url({{portrait-login}})"></div>
            <div class="news-caption">
                <h4 class="caption-title"><b>{{owner}}</b></h4>
                <p>{{department}}</p>
            </div>
        </div>

        <div class="login-container">

            <div class="login-header mb-30px">

                <img src="{{owner-logo}}" class="rounded mx-auto d-block user-access-logo"
                     alt="Default">
            </div>

            <div class="login-content">
                <form action="/User-Access" method="GET" class="fs-13px">
                    <div class="form-floating mb-15px">
                        <input type="text" autocomplete="on" class="form-control h-45px fs-13px"
                               placeholder="{{placeholder-email}}"
                               id="emailAddress">
                        <label for="emailAddress"
                               class="d-flex align-items-center fs-13px text-gray-600">{{label-email}}</label>
                    </div>
                    <div class="form-floating mb-15px">
                        <input type="password" autocomplete="on" class="form-control h-45px fs-13px"
                               placeholder="{{placeholder-password}}" id="password">
                        <label for="password"
                               class="d-flex align-items-center fs-13px text-gray-600">{{label-password}}</label>
                    </div>
                    <div class="form-check mb-30px">
                        <input class="form-check-input" type="checkbox" value="1" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">
                            {{label-remember-me}}
                        </label>
                    </div>
                    <div class="mb-15px">
                        <button type="submit" class="btn btn-theme d-block h-45px w-100 btn-lg fs-14px">
                            {{button-label-login}}
                        </button>
                    </div>
                    <div class="mb-40px pb-40px text-dark">
                        {{paragraph-0-0}} <a href="#" class="text-primary toggle-ua">{{paragraph-0-1}}</a>
                        {{paragraph-0-2}}
                    </div>
                    <hr class="bg-gray-600 opacity-2">
                    <div class="text-gray-600 text-center mb-0">
                        <a href="https://icaros.lh-2.net/" class="text-primary">&copy; Icaros Net - 2024</a>
                    </div>
                </form>
            </div>

            <div class="register-content d-none">
                <form action="/User-Access" method="GET" class="fs-13px">
                    <div class="mb-3">
                        <label class="mb-2">{{label-name}} <span class="text-danger">*</span></label>
                        <div class="row gx-3">
                            <div class="col-md-6 mb-2 mb-md-0">
                                <input type="text" autocomplete="on" class="form-control fs-13px"
                                       placeholder="{{placeholder-first-name}}">
                            </div>
                            <div class="col-md-6">
                                <input type="text" autocomplete="on" class="form-control fs-13px"
                                       placeholder="{{placeholder-last-name}}">
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="mb-2">{{label-email}} <span class="text-danger">*</span></label>
                        <input type="text" autocomplete="on" class="form-control fs-13px"
                               placeholder="{{placeholder-email}}">
                    </div>
                    <div class="mb-3">
                        <label class="mb-2">{{label-re-email}} <span class="text-danger">*</span></label>
                        <input type="text" autocomplete="on" class="form-control fs-13px"
                               placeholder="{{placeholder-re-email}}">
                    </div>
                    <div class="mb-4">
                        <label class="mb-2">{{label-password}} <span class="text-danger">*</span></label>
                        <input type="password" autocomplete="off" class="form-control fs-13px"
                               placeholder="{{placeholder-password}}">
                    </div>
                    <div class="form-check mb-4">
                        <input class="form-check-input" type="checkbox" value="" id="agreementCheckbox">
                        <label class="form-check-label" for="agreementCheckbox">
                            {{paragraph-1-0}} <a href="/User-Terms">{{paragraph-1-1}}</a> {{paragraph-1-2}} <a
                                    href="/Data-Policy">{{paragraph-1-3}}</a>, {{paragraph-1-4}} <a href="/Use-Cookies">{{paragraph-1-5}}</a>.
                        </label>
                    </div>
                    <div class="mb-4">
                        <button type="submit" class="btn btn-theme d-block w-100 btn-lg h-45px fs-13px">
                            {{button-label-register}}
                        </button>
                    </div>
                    <div class="mb-4 pb-5">
                        {{paragraph-2-0}} <a class="text-primary toggle-ua" href="#">{{paragraph-2-1}}</a>
                        {{paragraph-2-2}}.
                    </div>
                    <hr class="bg-gray-600 opacity-2">
                    <p class="text-center text-gray-600">
                        <a href="https://icaros.lh-2.net/" class="text-primary">&copy; Icaros Net - 2024</a>
                    </p>
                </form>
            </div>


        </div>

    </div>

    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>

</div>