<div id="app" class="app">

    <div class="login login-with-news-feed">

        <div class="news-feed">
            <div class="news-image" style="background-image: url(assets/img/sinaproc/voluntarios.jpg)"></div>
            <div class="news-caption">
                <h4 class="caption-title"><b>Sistema Nacional de Protección Civil</b></h4>
                <p>Dirección Nacional de Voluntariado.</p>
            </div>
        </div>


        <div class="login-container">

            <div class="login-header mb-30px">

                <img src="assets/img/sinaproc/sinaproc-logo.png" class="rounded mx-auto d-block user-access-logo"
                     alt="SINAPROC">
            </div>

            <div class="login-content">
                <form action="index.html" method="GET" class="fs-13px">
                    <div class="form-floating mb-15px">
                        <input type="text" class="form-control h-45px fs-13px" placeholder="Email Address"
                               id="emailAddress">
                        <label for="emailAddress" class="d-flex align-items-center fs-13px text-gray-600">Correo
                            Electronico</label>
                    </div>
                    <div class="form-floating mb-15px">
                        <input type="password" class="form-control h-45px fs-13px" placeholder="Password" id="password">
                        <label for="password" class="d-flex align-items-center fs-13px text-gray-600">Contraseña</label>
                    </div>
                    <div class="form-check mb-30px">
                        <input class="form-check-input" type="checkbox" value="1" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">
                            Recuerdame
                        </label>
                    </div>
                    <div class="mb-15px">
                        <button type="submit" class="btn btn-theme d-block h-45px w-100 btn-lg fs-14px">Iniciar Session
                        </button>
                    </div>
                    <div class="mb-40px pb-40px text-dark">
                        ¿Aún no eres voluntario? Click <a href="#" class="text-primary toggle-ua">aqui</a> para
                        registrarse.
                    </div>
                    <hr class="bg-gray-600 opacity-2">
                    <div class="text-gray-600 text-center  mb-0">
                        &copy; Icaros Net - 2024
                    </div>
                </form>
            </div>

            <div class="register-content d-none">
                <form action="index.html" method="GET" class="fs-13px">
                    <div class="mb-3">
                        <label class="mb-2">Nombre <span class="text-danger">*</span></label>
                        <div class="row gx-3">
                            <div class="col-md-6 mb-2 mb-md-0">
                                <input type="text" class="form-control fs-13px" placeholder="Primer nombre">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control fs-13px" placeholder="Primer apellido">
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">


                        <label class="mb-2">Correo <span class="text-danger">*</span></label>
                        <input type="text" class="form-control fs-13px" placeholder="Correo electronico">
                    </div>
                    <div class="mb-3">
                        <label class="mb-2">Repita Correo <span class="text-danger">*</span></label>
                        <input type="text" class="form-control fs-13px" placeholder="Repita el correo electronico">
                    </div>
                    <div class="mb-4">
                        <label class="mb-2">Contraseña <span class="text-danger">*</span></label>
                        <input type="password" class="form-control fs-13px" placeholder="Password">
                    </div>
                    <div class="form-check mb-4">
                        <input class="form-check-input" type="checkbox" value="" id="agreementCheckbox">
                        <label class="form-check-label" for="agreementCheckbox">
                            Al hacer clic en Registrarse, acepta nuestros <a href="#">Términos</a> y que ha leído
                            nuestra <a href="#">Política de datos</a>, incluido nuestro <a href="#">Uso de cookies</a>.
                        </label>
                    </div>
                    <div class="mb-4">
                        <button type="submit" class="btn btn-theme d-block w-100 btn-lg h-45px fs-13px">Registrar
                        </button>
                    </div>
                    <div class="mb-4 pb-5">
                        ¿Ya eres voluntario? Haz clic <a class="text-primary toggle-ua" href="#">aquí</a> para iniciar
                        sesión.
                    </div>
                    <hr class="bg-gray-600 opacity-2">
                    <p class="text-center text-gray-600">
                        &copy; Icaros Net - 2024
                    </p>
                </form>
            </div>


        </div>

    </div>

    {{app_setting}}

    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top"><i
                class="fa fa-angle-up"></i></a>

</div>