<div class="container-fluid py-4">
    <div class="row justify-content-center">
        <div class="col-lg-10">

            <ul class="nav nav-tabs nav-justified" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="nav-link {{active-terms}}" data-bs-toggle="tab" href="#terms">Condiciones de Servicio</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link {{active-privacy}}" data-bs-toggle="tab" href="#privacy">La Política de Privacidad</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link {{active-cookies}}" data-bs-toggle="tab" href="#cookies">La Política de Cookies</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link {{active-humanitarian}}" data-bs-toggle="tab" href="#humanitarian">Marco de Trabajo Humanitario</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane slide {{show-terms}} {{active-terms}}" id="terms">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h2 class="mb-0">Los Términos de Servicio</h2>
                            <p class="mb-0">
                                <span class="text-green-200 fw-bold">(Versión: 1.0.0)</span> Última actualización: {{last-update}}
                            </p>
                        </div>
                        <div class="card-body">
                            <section id="Introduction" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Introduction" title="Copy link to section"></i>
                                    <h3>1. Introducción</h3>
                                </div>

                                <p>Bienvenido a Last Hammer Framework y ADAH (Aplicación para el Desarrollo de Actividades Humanitarias). Estos Términos de Servicio ("Términos") rigen el uso de nuestra plataforma y nuestros servicios.</p>

                                <div class="mb-3">
                                    <p class="fw-bold">Estos Términos establecen:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Definición del Servicio:</b> Detalla lo que incluye y excluye el servicio ofrecido.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Condiciones de Uso:</b> Establece reglas como prohibiciones sobre mal uso, actividades ilegales o violaciones de propiedad intelectual.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Derechos del Usuario:</b> Define los derechos básicos de los usuarios (acceso, suspensión, terminación).
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Limitaciones de Responsabilidad:</b> Especifica aquello de lo que no es responsable el proveedor (fallos técnicos, mal uso, pérdidas indirectas).
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Modificaciones y Actualizaciones:</b> Describe cómo y cuándo pueden cambiar los términos.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Ley Aplicable y Resolución de Disputas:</b> Indica las leyes que rigen el tema y los métodos para resolver disputas.
                                        </li>
                                    </ul>
                                </div>
                                <p>Al acceder o utilizar Last Hammer Framework o ADAH, usted acepta estar sujeto a estos Términos. Si no está de acuerdo con alguna parte de estos términos, no podrá utilizar nuestros servicios.</p>

                                <div class="mb-3">

                                    <h4 class="ms-1">1.1 Ley Aplicable</h4>
                                    <p class="ms-1 mb-1">Estos Términos se rigen e interpretan de acuerdo con las leyes de la República de Panamá, que sirven como marco legal principal para el uso general de la plataforma.</p>

                                    <p class="ms-1 mb-1">Para instituciones o entidades que administran la plataforma en países fuera de Panamá, se requiere el cumplimiento de las leyes locales. Estas instituciones son responsables de asegurar que su uso de la plataforma cumpla con los marcos legales y regulatorios de los países donde se ofrecen sus operaciones o servicios.</p>

                                    <p class="ms-1 mb-1">En casos de conflicto entre la ley panameña y las leyes locales, las leyes locales del país donde se administra la plataforma tendrán precedencia para las actividades y servicios realizados dentro de esa jurisdicción, siempre que no entren en conflicto con los términos y políticas fundamentales establecidos por Icaros Net.</p>

                                </div>

                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Definitions" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Definitions" title="Copiar enlace a la sección"></i>
                                    <h3>2. Definiciones</h3>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">2.1 Partes y Plataforma</h4>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Nosotros", "nos", "nuestro" se refiere a Icaros Net, una empresa registrada en Ciudad de Panamá, Panamá.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Plataforma" se refiere a Last Hammer Framework y ADAH, incluyendo todos los sitios web, aplicaciones y servicios asociados.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Usuario", "tú", "tu" se refiere a cualquier individuo o entidad que utilice nuestra Plataforma.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Desarrollador" se refiere al equipo técnico responsable del desarrollo y mantenimiento de la plataforma.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Beneficiario" se refiere a las organizaciones humanitarias y entidades que utilizan la plataforma.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">2.2 Contenido y Datos</h4>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Contenido" se refiere a cualquier información, datos, texto, software, gráficos, mensajes, etiquetas u otros materiales disponibles en o a través de la Plataforma.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Información Técnica" incluye arquitectura del sistema, algoritmos y metodologías de desarrollo.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">2.3 Componentes Técnicos</h4>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Framework" se refiere a Last-Hammer 2, la plataforma central de desarrollo.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"ADAH" significa Aplicación para el Desarrollo de Actividades Humanitarias.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"API" se refiere a Interfaz de Programación de Aplicaciones utilizada para la integración del sistema.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Código Fuente" incluye todo el código del programa, scripts y archivos de configuración.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">2.4 Categorías de Usuarios</h4>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Miembros Básicos" son usuarios registrados con acceso limitado a la plataforma.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Miembros Avanzados" son usuarios que participan en actividades humanitarias con acceso limitado.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Colaboradores (de Entidades)" son socios externos que trabajan con la plataforma en entidades de gestión.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>"Personal Administrativo" son usuarios con privilegios de gestión en la plataforma.
                                        </li>
                                    </ul>
                                </div>

                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Service-Usage" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Service-Usage" title="Copy link to section"></i>
                                    <h3>3. Uso de los Servicios</h3>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">3.1 Accesibilidad de la Plataforma</h4>
                                    <p class="ms-1 mb-1">La plataforma sirve a la siguiente base de usuarios:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Todos los civiles de cualquier nación que puedan identificarse legalmente como nacionales o extranjeros
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Usuarios registrados bajo instituciones participantes
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Gestión Institucional:
                                            <ul class="list-unstyled">
                                                <li class="ms-3 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Las certificaciones, permisos de acceso y privilegios relacionados son gestionados por instituciones registradas
                                                </li>
                                                <li class="ms-3 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Cada institución maneja la verificación de usuarios y el control de acceso
                                                </li>
                                                <li class="ms-3 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Emisión y validación de certificaciones
                                                </li>
                                                <li class="ms-3 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Monitoreo de actividad de usuarios dentro del ámbito institucional
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">3.2. Elegibilidad</h4>
                                    <p class="ms-1 mb-1">Los usuarios deben cumplir uno de los siguientes criterios de elegibilidad:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Tener al menos 18 años para usar nuestros servicios de forma independiente.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Tener entre 13 y 17 años con consentimiento explícito y supervisión de los padres o tutor legal. En este caso:
                                            <ul class="list-unstyled">
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Un padre o tutor legal debe crear y administrar la cuenta
                                                </li>
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>La cuenta del menor debe estar vinculada a la cuenta principal del padre/tutor antes de la activación
                                                </li>
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>La cuenta del padre/tutor debe mantener un estado activo para que la cuenta del menor siga operativa
                                                </li>
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>El padre/tutor asume la responsabilidad total de monitorear las actividades del menor
                                                </li>
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>El padre/tutor recibirá notificaciones en tiempo real sobre:
                                                    <ul class="list-unstyled">
                                                        <li class="ms-2 me-2">
                                                            <i class="fa-solid fa-square me-1"></i>Intentos de inicio de sesión y sesiones activas
                                                        </li>
                                                        <li class="ms-2 me-2">
                                                            <i class="fa-solid fa-square me-1"></i>Creación y modificaciones de contenido
                                                        </li>
                                                        <li class="ms-2 me-2">
                                                            <i class="fa-solid fa-square me-1"></i>Interacciones con otros usuarios
                                                        </li>
                                                        <li class="ms-2 me-2">
                                                            <i class="fa-solid fa-square me-1"></i>Subidas y descargas de archivos
                                                        </li>
                                                        <li class="ms-2 me-2">
                                                            <i class="fa-solid fa-square me-1"></i>Cambios en la configuración de la cuenta
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">3.3. Registro de Cuenta</h4>
                                    <p class="ms-1 mb-1">Es posible que necesite crear una cuenta para acceder a ciertas funciones de nuestra Plataforma. Usted acepta proporcionar información precisa, actual y completa durante el proceso de registro y actualizar dicha información para mantenerla precisa, actual y completa. Usted es responsable de salvaguardar la contraseña que utiliza para acceder a la Plataforma y de cualquier actividad o acción bajo su contraseña.</p>
                                </div>

                                <div class="mb-3">
                                    <h4 class="ms-1">3.4. Uso Aceptable</h4>
                                    <p class="ms-1 mb-1">Usted acepta usar nuestra Plataforma solo para fines legales y de acuerdo con estos Términos. Usted acepta no usar la Plataforma:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>De cualquier manera que viole cualquier ley o regulación nacional o internacional aplicable.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Para transmitir o procurar el envío de cualquier material publicitario o promocional, incluyendo cualquier "correo basura", "cadena", "spam" o cualquier otra solicitud similar.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Para suplantar o intentar suplantar a Icaros Net, un empleado de la empresa, otro usuario o cualquier otra persona o entidad.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-1"></i>Para participar en cualquier otra conducta que restrinja o inhiba el uso o disfrute de la Plataforma por parte de cualquier persona, o que, según lo determinemos, pueda dañar a Icaros Net o a los usuarios de la Plataforma o exponerlos a responsabilidad legal.
                                        </li>
                                    </ul>
                                </div>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>
                            <section id="Intellectual-Property" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Intellectual-Property" title="Copy link to section"></i>
                                    <h3>4. Derechos de Propiedad Intelectual</h3>
                                </div>
                                <h4 class="ms-1">4.4 Derechos de Uso</h4>
                                <p class="ms-1 mb-1">La plataforma opera bajo la siguiente estructura de derechos de uso:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Los usuarios mantienen el control total sobre sus datos personales mientras usan la plataforma.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Las implementaciones técnicas están licenciadas para su uso dentro del alcance de la plataforma.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Los componentes del framework se proporcionan bajo términos específicos de licencia por Icaros Net.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Las modificaciones a los componentes frontend y backend del núcleo requieren autorización expresa de Icaros Net.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Los derechos de distribución y reutilización están estrictamente controlados.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Cualquier cambio realizado en la plataforma que afecte la gestión de información o usuarios será notificado en el registro de cambios (changelog). Si no estás de acuerdo con estos cambios, se recomienda que solicites la desactivación inmediata de tu cuenta.
                                    </li>
                                </ul>
                            </section>
                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="User-Classifications" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="User-Classifications" title="Copy link to section"></i>
                                    <h3>5. Clasificación de Usuarios</h3>
                                </div>
                                <div class="mb-4">
                                    <h4 class="ms-1">5.1 Miembros Básicos</h4>
                                    <p class="ms-1 mb-1">Usuarios con acceso limitado a la plataforma:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso a las funcionalidades básicas de la plataforma.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Capacidad para visualizar recursos públicos (capacitación, anuncios, noticias) asociados a las instituciones donde están registrados.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Participación restringida en actividades: los usuarios solo pueden participar en actividades a las que estén vinculados o donde su participación haya sido aprobada.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso a materiales de capacitación públicos: los usuarios tendrán acceso al contenido de las capacitaciones en las que hayan participado.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Capacidades básicas de generación de reportes según su perfil y permisos otorgados por su institución afiliada.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Supervisión por parte de una o más instituciones que gestionen su perfil y participación.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso completo a la Red Social Hero: podrán invitar y agregar a compañeros ya registrados, gestionar su perfil y controlar qué comparten con sus contactos.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">5.2 Miembros Avanzados</h4>
                                    <p class="ms-1 mb-1">Estos usuarios tienen los privilegios de los miembros básicos más lo siguiente:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Activación automática cuando una institución les asigna un cargo o rango (jerárquico, administrativo o como formador).
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso y participación en actividades de respuesta a emergencias basadas en la integración de recursos humanos por parte de la institución a la que pertenecen.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso a formación avanzada, con la capacidad de crear eventos de certificación y sesiones de capacitación individual bajo su coordinación.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso a todos los materiales de capacitación proporcionados por las instituciones a las que pertenecen.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">5.3 Miembros Colaboradores (Personal de las Entidades)</h4>
                                    <p class="ms-1 mb-1">Socios externos que trabajan en la gestión de la plataforma tendrán los privilegios de los miembros básicos y avanzados, además de:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso al Programa de Colaboradores: desarrollo y diseño de reglas de negocio para la gestión de sus instituciones.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Capacidad para crear y compartir recursos de todo tipo (capacitaciones, eventos, emergencias, entre otros).
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Posibilidad de crear y coordinar operaciones conjuntas.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Acceso a herramientas especializadas.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">5.4 Personal Administrativo (Personal de las Entidades)</h4>
                                    <p class="ms-1 mb-1">El personal administrativo con privilegios ampliados tiene todos los beneficios de los miembros básicos, avanzados y colaboradores, además de:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Autoridad completa de administración del sistema, incluyendo gestión de roles institucionales y niveles de acceso.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Capacidades completas de gestión de usuarios, como creación, modificación y supervisión de cuentas institucionales.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Control estratégico de asignación y distribución de recursos a nivel institucional.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Herramientas avanzadas de análisis y generación de informes con detalles sobre métricas de desempeño institucional.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Derechos de administración técnica y configuración completa del sistema, incluyendo ajustes de seguridad y parámetros globales.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">5.5 Gestión de Niveles de Acceso</h4>
                                    <p class="ms-1 mb-1">Marco de seguridad y control de acceso (para desarrollo y administración del personal de Icaros Net):</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Gestión de permisos basada en roles.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Aplicación de jerarquías de acceso.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Sistemas de monitoreo de actividades.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Revisiones regulares de acceso.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Cumplimiento de estándares de seguridad.
                                        </li>
                                    </ul>
                                </div>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Contact-Us" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Contact-Us" title="Copy link to section"></i>
                                    <h3>6. Soporte y Resolución de Consultas</h3>
                                </div>
                                <div class="mb-4">
                                    <h4 class="ms-1">6.1 Preguntas Frecuentes (FAQ)</h4>
                                    <p class="ms-1 mb-1">Los usuarios pueden acceder a una sección de Preguntas Frecuentes (FAQ) que proporciona respuestas a consultas comunes sobre el uso del sistema, reglas generales y problemas técnicos.</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Una FAQ general está disponible para todos los usuarios en la página principal de la plataforma.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Cada institución afiliada gestionará su propia sección personalizada de FAQ, adaptada a sus procesos internos y usuarios específicos.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">6.2 Canales de Soporte</h4>
                                    <p class="ms-1 mb-1">La plataforma ofrece múltiples canales de soporte para resolver problemas técnicos o relacionados con el servicio:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i><b>Soporte General de la Plataforma:</b>
                                            <ul class="list-unstyled">
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Disponible para todos los usuarios mediante un formulario de contacto en el sitio web oficial.
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i><b>Soporte Institucional:</b>
                                            <ul class="list-unstyled">
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Cada institución afiliada debe mantener su propio canal de soporte.
                                                </li>
                                                <li class="ms-2 me-2">
                                                    <i class="fa-regular fa-circle me-1"></i>Estos canales incluyen contacto directo con representantes institucionales y deben garantizar servicio en horarios acordados.
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">6.3 Contáctanos</h4>
                                    <p class="ms-1 mb-1">El sistema incluye un formulario "Contáctanos" en dos niveles:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>General: Ubicado en la página principal del sistema para consultas globales.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Institucional: Cada institución debe habilitar su propia sección de contacto visible para sus usuarios y socios colaboradores.
                                        </li>
                                    </ul>
                                </div>

                                <div class="mb-4">
                                    <h4 class="ms-1">6.4 Responsabilidades de las Instituciones Afiliadas</h4>
                                    <p class="ms-1 mb-1">Cada institución es responsable de garantizar que los usuarios afiliados tengan acceso a:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Información clara y actualizada en su sección de FAQ.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Respuestas oportunas a las consultas enviadas a través de sus canales de soporte.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-circle me-2"></i>Transparencia al comunicar problemas técnicos, cambios en el sistema o cualquier actividad que pueda afectar a los usuarios.
                                        </li>
                                    </ul>
                                </div>
                            </section>

                        </div>
                    </div>
                </div>

                <div class="tab-pane slide {{show-privacy}} {{active-privacy}}" id="privacy">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h2 class="mb-0">Política de Privacidad</h2>
                            <p class="mb-0">
                                <span class="text-green-200 fw-bold">(Version: 1.0.0)</span> Última Actualización: {{last-update}}
                            </p>
                        </div>
                        <div class="card-body">
                            <section id="Introduction" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Introduction" title="Copy link to section"></i>
                                    <h3>1. Introducción</h3>
                                </div>

                                <p>Esta Política de Privacidad explica cómo Icaros Net ("nosotros", "nuestro" o "nos") recopila, utiliza y protege su información personal cuando utiliza Last Hammer Framework y ADAH (Aplicación para el Desarrollo de Actividades Humanitarias) (colectivamente, la "Plataforma"). Estamos comprometidos a garantizar que su privacidad esté protegida conforme a las leyes y regulaciones aplicables.</p>

                                <div class="mb-3">
                                    <p class="fw-bold">Esta Política de Privacidad establece:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Tipos de Datos Recopilados:</b> Incluye datos personales como nombre, correo electrónico, dirección IP, entre otros.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Propósito del Uso de los Datos:</b> Describe por qué se utilizan los datos (marketing, análisis, funcionalidad del servicio).
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Derechos del Usuario:</b> Menciona derechos como acceso, rectificación, eliminación y objeción.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Seguridad de los Datos:</b> Explica las medidas implementadas para proteger los datos del usuario.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Terceros Involucrados:</b> Indica si los datos se comparten con socios, subcontratistas o terceros.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Almacenamiento y Retención de Datos:</b> Detalla el tiempo de retención de los datos.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Cumplimiento Legal:</b> Hace referencia a regulaciones como GDPR, CCPA u otras leyes locales.
                                        </li>
                                    </ul>
                                </div>

                                <h4 class="ms-1 mb-1">1.1 Alcance de la Aplicación en el Procesamiento de Datos (Capacidades Principales de la Plataforma)</h4>

                                <p class="ms-1 mb-1">Esta plataforma actúa como una herramienta integral para el liderazgo y la gestión de equipos de trabajo humanitarios, ofreciendo servicios alineados con políticas institucionales de gestión. El alcance inicial abarca:</p>

                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Operaciones y actividades humanitarias.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Registro de usuarios y gestión de cuentas.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Sistemas de asignación y seguimiento de recursos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Herramientas de comunicación y colaboración.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Procesos de formación y certificación.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">1.2 Marco Legal</h4>
                                <p class="ms-1 mb-1">Nuestra plataforma opera en cumplimiento con las siguientes normativas y estándares internacionales de protección de datos::</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i><b>Ley 81 de 26 de marzo de 2019 (Panamá):</b> Establece disposiciones generales para la protección de datos personales en la jurisdicción panameña.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i><b>Reglamento General de Protección de Datos (GDPR):</b> Proporciona principios fundamentales para la recopilación, uso y transferencia de datos dentro de la Unión Europea.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i><b>Estándares Internacionales Humanitarios:</b> Incluyen directrices de responsabilidad de datos de la ONU OCHA y estándares específicos para el sector humanitario.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i><b>Normativas Regionales de Protección de Datos:</b> Consideran regulaciones específicas de América Latina y otras regiones aplicables.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i><b>Transferencias Internacionales de Datos:</b> Gestionadas conforme a cláusulas contractuales estándar y reglas corporativas vinculantes.
                                    </li>
                                </ul>

                                <p class="ms-1 mb-1">Además, cumplimos con estándares específicos del sector, tales como:</p>

                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Principios de Privacidad de la OEA (Organización de Estados Americanos).
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Marco de Privacidad de APEC (Cooperación Económica Asia-Pacífico).
                                    </li>
                                </ul>

                                <p class="ms-1 mb-2">Esta sección garantiza la transparencia y el cumplimiento de las normativas aplicables, priorizando la protección de los datos personales de nuestros usuarios. Puede encontrar más detalles sobre este marco en la pestaña "Marco de Datos Humanitarios".</p>

                                <h4 class="ms-1 mb-1">1.3 Principios Clave</h4>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Transparencia en la recopilación y procesamiento de datos: Comunicación clara sobre cómo recopilamos, usamos y manejamos los datos, asegurando que los usuarios comprendan cada paso del proceso.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Limitación del propósito y minimización de datos: Recopilamos solo los datos esenciales necesarios para propósitos específicos, almacenándolos únicamente durante el tiempo necesario.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Medidas de seguridad y confidencialidad: Implementación de salvaguardas técnicas y organizacionales para proteger los datos contra accesos no autorizados, brechas y ciberamenazas.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Derechos del usuario y control sobre los datos personales: Empoderamos a los usuarios con pleno control sobre su información, incluyendo derechos para acceder, modificar, exportar y eliminar sus datos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Documentación de cumplimiento y responsabilidad: Mantenemos registros detallados de todas las actividades de procesamiento de datos y realizamos auditorías regulares para garantizar la adherencia a regulaciones y estándares de privacidad.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Integridad y calidad de los datos: Aseguramos que todos los datos almacenados sean precisos, completos y se validen regularmente mediante procesos sistemáticos de verificación.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Protección de datos transfronterizos: Gestionamos las transferencias internacionales de datos con salvaguardas adecuadas y cumplimiento de normativas regionales.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Protocolo de respuesta ante incidentes: Mantenemos procedimientos claros para detectar, reportar y manejar brechas de datos o incidentes de seguridad.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Privacidad desde el diseño: Incorporamos consideraciones de privacidad en todos los aspectos del desarrollo y operación de la plataforma desde su concepción.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Evaluaciones regulares de impacto en la privacidad: Realizamos evaluaciones sistemáticas para identificar y minimizar los riesgos de privacidad en las operaciones de la plataforma.
                                    </li>
                                </ul>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Information-We-Collect" class="mb-2">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Information-We-Collect" title="Copy link to section"></i>
                                    <h3>2. Información que Recopilamos</h3>
                                </div>

                                <h4 class="ms-1 mb-1">2.1 Información Personal</h4>
                                <p class="ms-1 mb-1">Recopilamos y procesamos las siguientes categorías de información personal. Esta sección detalla los puntos en los que se recopila dicha información, incluyendo los sistemas y escenarios que facilitan este proceso:</p>

                                <h5 class="ms-2 mb-1">2.1.1 Información Básica de Identidad y Profesional</h5>
                                <ul class="list-unstyled ms-1 mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Nombre legal completo y nombres preferidos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Fecha de nacimiento para verificación de edad.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Números de identificación emitidos por el gobierno (cuando sea necesario).
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Fotografías de perfil (opcional).
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Afiliaciones organizativas y roles.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Certificaciones y licencias profesionales.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Registros de formación y calificaciones.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Áreas de especialización.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Historial y experiencia como voluntario.
                                    </li>
                                </ul>

                                <p class="ms-2 mt-1 mb-1">Es posible que sea necesario recopilar datos adicionales y, cada vez que se agreguen datos nuevos, se proporcionará una explicación específica de cómo se utilizará la información.</p>

                                <h5 class="ms-2 mb-1">2.1.2 Información de Contacto</h5>
                                <ul class="list-unstyled ms-1 mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Direcciones de correo electrónico primarias y secundarias.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Números de teléfono móvil y fijo.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Detalles de contacto de emergencia.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Dirección física (residencial y/o postal).
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Métodos y horarios preferidos de contacto.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">2.2 Datos de Uso</h4>
                                <p class="ms-1 mb-1">Nuestra plataforma recopila automáticamente datos técnicos y de comportamiento, incluyendo:</p>
                                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-3">
                                    <div class="col">
                                        <h5 class="ms-2 mb-1">2.2.1 Información de Acceso</h5>
                                        <ul class="list-unstyled ms-1 mb-1">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Marcas de tiempo de inicio de sesión y duración.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Identificadores de sesión.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Patrones de acceso y frecuencia.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Ubicación geográfica del acceso.
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <h5 class="ms-2 mb-1">2.2.2 Información del Dispositivo</h5>
                                        <ul class="list-unstyled ms-1 mb-1">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Tipo y modelo del dispositivo.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Sistema operativo y versión.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Resolución y orientación de la pantalla.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Proveedor de servicios móviles (si aplica).
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Especificaciones de hardware.
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <h5 class="ms-2 mb-1">2.2.3 Datos del Navegador</h5>
                                        <ul class="list-unstyled ms-1 mb-1">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Tipo y versión del navegador.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Preferencias de idioma.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Instalación de complementos.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Preferencias y configuraciones de cookies.
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <h5 class="ms-2 mb-1">2.2.4 Información de la Red</h5>
                                        <ul class="list-unstyled ms-1 mb-1">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Direcciones IP y rangos.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Tipo de conexión de red.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Detalles del proveedor de servicios de internet.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Detección de uso de VPN.
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <h5 class="ms-2 mb-1">2.2.5 Métricas de Interacción</h5>
                                        <ul class="list-unstyled ms-1 mb-1">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Páginas y funciones a las que se accede.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Patrones de navegación.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Tiempo empleado en diferentes secciones.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Actividades de descarga y carga.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Tasas de finalización de formularios.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Encuentros y reportes de errores.
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Data-Protection-Compliance" class="mb-4">
                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Data-Protection-Compliance" title="Copy link to section"></i>
                                    <h3>3. Cumplimiento con la Protección de Datos</h3>
                                </div>

                                <h4 class="ms-1 mb-1">3.1 Protocolos de Confidencialidad de Datos</h4>
                                <p>Implementamos medidas completas de confidencialidad, incluyendo:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Cifrado de extremo a extremo: Aseguramos que las comunicaciones sean accesibles solo para los usuarios finales.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Control de acceso basado en roles (RBAC): Se implementan niveles granulares de acceso, como:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-1"></i>Por módulo (ej. acceso solo a "Organización", no a "Operaciones").
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-1"></i>Por acción (ej. ver datos sin modificarlos).
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-1"></i>Por componentes de la interfaz (ej. botones específicos o formularios).
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Autenticación multifactor (MFA): La MFA es un proceso de autenticación en el que el usuario debe proporcionar más de una forma de identificación para acceder al sistema. Esto suele implicar algo como un código de verificación adicional por correo electrónico, mensaje de texto/Whatsapp, una huella digital o reconocimiento facial en los casos en que el usuario indique que lo desea.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Gestión de sesiones y controles de tiempo de espera: La gestión de sesiones implica controlar el tiempo durante el cual un usuario está activo en un sistema. Los controles de tiempo de espera especifican cuánto tiempo puede estar inactiva una sesión antes de que el sistema la cierre automáticamente. Hemos considerado que el usuario debe decidir esto, incluidas las sesiones de tiempo ilimitado, hasta sesiones de 15 minutos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Registro y monitoreo del acceso a los datos: el registro y monitoreo del acceso a los datos implica la creación de registros detallados de cada acción realizada sobre los datos, como quién accedió a ellos, cuándo y qué datos se vieron o modificaron. Además, el monitoreo constante permite detectar actividades sospechosas o no autorizadas en tiempo real.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Acuerdos de confidencialidad para todos los usuarios del sistema: Los acuerdos de confidencialidad son contratos legales que garantizan que los empleados, contratistas y otros usuarios del sistema comprendan y acepten mantener la privacidad de los datos a los que acceden. Estos acuerdos suelen definir las responsabilidades y las consecuencias legales de violar la confidencialidad. Creemos que las instituciones deberían regular esto; cada usuario debería aceptar los acuerdos de confidencialidad de las instituciones en las que participa.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">3.2 Auditorías de Seguridad y Actualizaciones</h4>
                                <p>Mantenemos la seguridad del sistema mediante:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Evaluaciones de seguridad mensuales: son revisiones programadas que se realizan mensualmente para identificar vulnerabilidades o problemas en la seguridad del sistema. Esto incluye análisis de configuración, acceso y amenazas potenciales.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Pruebas de penetración trimestrales: Las pruebas de penetración (o pentesting) son una simulación de ataques realizadas por expertos en seguridad para identificar y explotar vulnerabilidades en el sistema, tal y como lo haría un hacker real.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Escaneo de seguridad automatizado: utilice herramientas automatizadas para escanear aplicaciones, redes o infraestructura en busca de vulnerabilidades como configuraciones incorrectas, software desactualizado o agujeros de seguridad.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Actualizaciones y parches de software regulares: es el proceso de instalar actualizaciones y parches en el software para corregir errores, mejorar la funcionalidad y, lo más importante, resolver vulnerabilidades de seguridad.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Planificación y prueba de la respuesta a incidentes: implica desarrollar y probar procedimientos claros para responder a incidentes de seguridad, como violaciones de datos o ataques cibernéticos. Esto incluye definir funciones, responsabilidades y pasos a seguir en caso de emergencia.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Monitoreo del cumplimiento de seguridad: Es el proceso de monitorear continuamente que el sistema cumpla con los estándares y regulaciones de seguridad aplicables, como GDPR, ISO 27001, HIPAA, entre otros.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">3.3 Control de Datos del Usuario</h4>
                                <p class="ms-1 mb-1">Los usuarios mantienen el control sobre sus datos mediante:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Configuraciones completas de privacidad.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Capacidades de exportación de datos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Solicitudes de acceso, corrección y eliminación de datos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Opciones de gestión de consentimiento.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Informes transparentes sobre el uso de datos.
                                    </li>
                                </ul>
                                <p class="ms-1 mb-1">
                                    <b>Gestión del Consentimiento</b> Solicitamos consentimiento explícito antes de recopilar datos sensibles.
                                    <i>Por ejemplo:</i> antes de registrar su foto de perfil, aparecerá un aviso solicitando autorización específica.
                                </p>
                                <p class="ms-1 mb-2">
                                    <b>Procedimientos para Ejercer Derechos</b> Para acceder, rectificar o eliminar sus datos, envíe una solicitud a privacy@icaros.net. We will respond within 15 business days.
                                    <i>Example:</i> Responderemos en un plazo de 15 días hábiles. Ejemplo: si desea corregir un error en su dirección, indique su información actual y la nueva en el correo.
                                </p>

                                <h4 class="ms-1 mb-1">3.4 Registros del Procesamiento de Datos</h4>
                                <p class="ms-1 mb-1">Mantenemos registros detallados de:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Actividades de tratamiento de datos: Se refiere al registro de todas las operaciones realizadas sobre datos personales, como la recogida, el almacenamiento, el uso, la modificación y la supresión. Esto incluye información sobre quién procesó los datos, por qué y cómo.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Operaciones de transferencia de datos: Esto implica documentar cada vez que se transfieren datos de una ubicación a otra, ya sea dentro de la organización, entre sistemas o a terceros, incluidas las transferencias internacionales.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Informes de incidentes de seguridad: son registros detallados de cualquier incidente que comprometa la seguridad de los datos, como acceso no autorizado, pérdida de información o ataques cibernéticos.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Registro de consentimiento de los usuarios: Se refiere a conservar evidencia de que los usuarios han dado su consentimiento para el tratamiento de sus datos. Esto puede incluir formularios firmados, registros electrónicos de aceptación o confirmaciones explícitas en plataformas digitales.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Solicitudes de acceso a datos: Son solicitudes que realizan los usuarios para acceder a sus datos personales, corregir errores, limitar su uso o eliminarlos (conocidos como derechos ARCO: Acceso, Rectificación, Cancelación y Oposición).
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Documentación de cumplimiento: incluye todos los documentos necesarios para demostrar que la organización cumple con las leyes y regulaciones de protección de datos. Esto puede incluir políticas internas, evaluaciones de impacto, acuerdos con terceros y auditorías.
                                    </li>
                                </ul>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Data-Categories" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Data-Categories" title="Copy link to section"></i>
                                    <h3>4. Data Categories</h3>
                                </div>

                                <h4 class="ms-1 mb-1">4.1 Personal Information</h4>
                                <p class="ms-1 mb-1">The following categories of personal information are collected and managed, This section organizes the collected information into categories used for managing and utilizing data in compliance with privacy standards:</p>

                                <h5 class="ms-1 mb-1">Basic Identification Data</h5>

                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Full legal name and any preferred names: Includes the user's official name as per legal documents (e.g., passport, national ID) and any nicknames or preferred names for personalized interaction.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Date of birth and nationality: The date of birth is used for age verification or providing tailored services based on age demographics. Nationality may influence access to region-specific services or compliance with local regulations.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Government-issued identification numbers: Covers identification numbers such as passport numbers, national ID numbers, tax identification numbers, or social security numbers for identity verification purposes.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Profile photos and identification documents: Includes user-uploaded profile images and scanned copies of identification documents necessary for security purposes or verifying authenticity.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Digital signatures and authentication credentials: Data related to electronic signatures, authentication tokens, or credentials used to validate secure access or conduct sensitive operations.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Contact Information</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Primary and secondary email addresses: Includes the user's main email address used for account management, notifications, and communication. Secondary emails provide redundancy for recovery purposes or alternative contact options.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Mobile and landline phone numbers: Covers mobile numbers for SMS notifications, two-factor authentication, and urgent communications, while landline numbers (if provided) serve as alternative contact points.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Current residential address: Captures the user's current residential or mailing address for verifying service eligibility, compliance with jurisdictional requirements, or for correspondence purposes.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Emergency contact details: Stores contact information for individuals designated to be contacted in case of emergencies or for verification in exceptional circumstances.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Preferred communication methods: Reflects user preferences regarding how they wish to be contacted (e.g., via email, phone, or other specified channels) and their preferred time for communication.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Professional Certifications</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Professional licenses and permits: Encompasses licenses issued by governmental or regulatory bodies that authorize the user to perform specific professional activities, such as medical licenses, engineering permits, or legal practice certificates.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Technical certifications and validations: Includes certifications obtained from industry-recognized institutions that validate specific technical skills or expertise, such as cloud certifications, programming certifications, or safety validations (e.g., OSHA).
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Specialized training certificates: Refers to documentation of training programs or workshops attended by the user that demonstrate specialized skill sets, such as first-aid training, advanced software workshops, or leadership development courses.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Academic credentials and diplomas: Covers degrees and certifications from accredited educational institutions, such as bachelor’s, master’s, or doctoral degrees, as well as high school diplomas or equivalent qualifications.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Professional association memberships: Includes memberships in industry-related associations or bodies, such as bar associations for lawyers, IEEE for engineers, or PMI for project managers. These memberships often signify professional credibility and networking within specific fields.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Training Records</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Completed training courses and workshops: This includes records of formal training sessions or workshops that users have completed, covering both online and in-person formats. Examples could include safety training, advanced technical workshops, or role-specific onboarding sessions.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Assessment scores and evaluations: Refers to grades, performance metrics, or feedback received from assessments, tests, or evaluations conducted during or after the training. This helps track the user's proficiency and understanding.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Skills development progress: Captures data on a user's advancement over time in specific skill areas, providing insights into growth, strengths, and areas for improvement. This could include tracking milestones within skill-building programs.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Specialization areas and expertise levels: Includes detailed categorization of the user’s expertise in certain domains or industries, highlighting specialties that are recognized through certifications or demonstrated competence.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Continuing education credits: Refers to credits earned for participation in certified continuing education programs. These credits are often mandatory in industries like healthcare or law to maintain active licensure.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Participation History</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Mission involvement and roles: Captures the specific missions, projects, or programs in which the user has participated. This includes details such as mission names, timelines, and the roles or responsibilities undertaken during these engagements.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Volunteer hours and contributions: Tracks the total hours dedicated by the user to volunteering activities. Contributions may also include specific tasks, milestones achieved, or resources provided during their involvement.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Project participation records: Documents the projects the user has actively contributed to, including their scope, objectives, and individual contributions. This may also include collaborative efforts or cross-functional involvement.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Leadership positions held: Reflects any formal or informal leadership roles the user has undertaken, such as team leader, project manager, or coordinator roles. Details may also include the duration and impact of their leadership.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Recognition and achievements: Includes awards, honors, or commendations received by the user for their work or contributions. This could also encompass milestones achieved within projects or missions.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">4.2 Operational Data</h4>
                                <p class="ms-1 mb-1">The following operational data is maintained for organizational effectiveness:</p>

                                <h5 class="ms-1 mb-1">Activity Logs</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>System access and authentication records: Logs tracking user logins, including timestamps, IP addresses, device details, and authentication methods used (e.g., multi-factor authentication). These ensure system integrity and trace unauthorized access attempts.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Resource utilization tracking: Monitors how users interact with system resources, such as bandwidth usage, storage access, and file downloads, to optimize platform performance.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Communication logs and timestamps: Includes records of communications sent and received via the platform (e.g., messages, emails, notifications), along with their respective timestamps for audit and reference purposes.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Document access and modification history: Tracks user actions on documents, including viewing, editing, downloading, and sharing activities, to maintain data integrity and accountability.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Training participation records: Details user attendance, progress, and completion of training sessions or workshops, often tied to performance and compliance tracking.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Mission Reports</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Mission objectives and outcomes: Summarizes mission goals, key deliverables, and their achieved outcomes, providing insights into operational success and areas for improvement.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Team composition and roles: Documents team structures, including the roles and responsibilities of each participant, to ensure clarity in accountability and task allocation.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Resource deployment details: Includes a breakdown of deployed resources such as equipment, vehicles, and personnel, along with their locations and timelines.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Incident reports and resolutions: Captures details of any incidents that occurred during missions, their causes, impacts, and the measures taken to resolve them.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Performance metrics and evaluations: Quantitative and qualitative data assessing mission efficiency, resource utilization, and individual/team contributions.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Resource Allocation Records</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Equipment and material assignments: Tracks what equipment or materials were assigned to whom, when, and for what purpose, ensuring accountability and optimal use.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Personnel deployment schedules: Includes detailed schedules of staff or volunteer assignments, timelines, and roles for missions or projects.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Budget allocation and tracking: Monitors allocated budgets, expenditures, and financial compliance, providing transparency and facilitating audits.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Inventory management records: Tracks inventory levels, usage patterns, and restocking needs to ensure availability and proper resource management.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Resource utilization analytics: Analyzes data on how resources are used, identifying inefficiencies or patterns for strategic decision-making.
                                    </li>
                                </ul>

                                <h5 class="ms-1 mb-1">Emergency Response Documentation</h5>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Emergency action plans and protocols: Outlines predefined steps and protocols to follow during emergencies, ensuring rapid and effective responses.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Response team assignments: Documents team member roles and responsibilities during emergencies, clarifying reporting structures and duties.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Incident assessment reports: Evaluates incidents post-occurrence to determine their impact, root causes, and areas needing corrective actions.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Communication logs during emergencies: Tracks all communications exchanged during an emergency to ensure transparency and facilitate after-action reviews.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Post-incident analysis and recommendations: Summarizes key lessons learned and recommendations for future improvements based on incident evaluations.
                                    </li>
                                </ul>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="International-Data-Transfers" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="International-Data-Transfers" title="Copy link to section"></i>
                                    <h3>5. International Data Transfers</h3>
                                </div>

                                <h4 class="ms-1 mb-1">5.1 International Data Transfer and Localizations</h4>
                                <p class="ms-1 mb-1">Our system implements rigorous protocols for international data transfer, complying with legal and security standards. This includes::</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>End-to-end encryption: to protect data during transfer: Ensures that data is encrypted at the source and only decrypted at its destination, protecting it from interception or unauthorized access during transmission.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Secure data routing through certified network infrastructure: Data is transmitted over networks certified to meet stringent security and compliance standards, minimizing risks associated with insecure pathways.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Real-time monitoring of data flows to ensure their integrity: Continuous tracking and analysis of data transfers detect anomalies or unauthorized activities, preserving data accuracy and confidentiality.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Localized data storage in data centers: Data centers located within Panama and other approved jurisdictions comply with local legal requirements and improve accessibility while maintaining security.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Compliance with local and international regulations: Adherence to frameworks like Panama Law 81, GDPR, and OAS regulations ensures lawful data handling across borders.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Privacy impact assessments before international transfers: Conducting evaluations to identify and mitigate risks associated with transferring personal data internationally, ensuring robust compliance and user protection.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">5.2 International Compliance Standards</h4>
                                <p class="ms-1 mb-1">We adhere to multiple international data protection frameworks:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Panama Data Protection Law (Law 81 of March 26, 2019): Regulates personal data collection, processing, and storage, ensuring the protection of users’ rights within Panamanian jurisdiction.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>General Data Protection Regulation (GDPR) principles: Upholds core principles like data minimization, lawful processing, and user consent for European Union data subjects.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Asia-Pacific Economic Cooperation (APEC) Privacy Framework: Provides guidelines for ensuring privacy and data protection in the Asia-Pacific region.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Organization of American States (OAS) Privacy Principles: Establishes shared privacy guidelines for member states to promote consistency in data handling.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>International humanitarian data protection standards: Ensures compliance with ethical data usage and protection in humanitarian operations, respecting the sensitivity of such information.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">5.3 Data Localization Requirements</h4>
                                <p class="ms-1 mb-1">Our platform maintains specific requirements for data storage and processing:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Primary data storage within Panama's jurisdiction: Guarantees that core user data remains within Panama, adhering to local legal and privacy obligations.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Regional data centers for improved access and compliance: Enhances service performance and ensures compliance with regional laws through strategically located data centers.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Local backup systems in approved jurisdictions: Maintains backup copies of data within legally sanctioned regions, ensuring disaster recovery without compromising compliance.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Geographic restrictions on sensitive data processing: Prevents sensitive data from being processed in jurisdictions that do not meet required legal or ethical standards.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Country-specific data retention policies: Aligns data storage and deletion practices with the unique legal requirements of each country where operations occur.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">5.4 Transfer Impact Assessments</h4>
                                <p class="ms-1 mb-1">We conduct regular assessments for international transfers:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Privacy impact evaluations for each destination country: Analyzes the privacy risks and legal compatibility of transferring data to a specific jurisdiction.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Security infrastructure verification: Ensures that the receiving entity or infrastructure meets the required security benchmarks.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Legal compliance validation: Confirms that international transfers adhere to applicable legal standards, such as GDPR or local laws.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Risk mitigation strategies: Implements measures to reduce potential risks, such as adopting advanced encryption methods or limiting the scope of transferred data.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Regular updates to transfer protocols: Ensures that transfer methods and safeguards remain compliant with evolving international standards and threats.
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">5.5 International Data Processing Agreements</h4>
                                <p class="ms-1 mb-1">Our transfers are governed by:</p>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Standard contractual clauses for international transfers: Utilizes predefined legal agreements to ensure compliance with international data transfer regulations.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Binding corporate rules for internal transfers: Governs data transfers within an organization across borders while adhering to strict compliance standards.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Data processing agreements with international partners: Establishes contracts that outline responsibilities and safeguards for partners handling data.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Specific humanitarian data sharing protocols: Tailored protocols for sharing sensitive data in humanitarian contexts, prioritizing privacy and ethical considerations.
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Emergency response data transfer procedures: Predefined processes for securely sharing critical data during emergencies, ensuring timely response without compromising security.
                                    </li>
                                </ul>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Fraud-Prevention-and-Security" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Fraud-Prevention-and-Security" title="Copy link to section"></i>
                                    <h3>6. Fraud Prevention and Security</h3>
                                </div>

                                <h4 class="ms-1 mb-1">6.1 Anti-Fraud Measures</h4>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Email Security:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Official email domain verification: Ensures all emails originating from the platform are sent through authenticated and trusted domains, reducing spoofing and impersonation risks.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Digital signature implementation: Adds cryptographic signatures to emails to verify their authenticity and integrity, ensuring they are not altered in transit.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Phishing prevention protocols: Includes training users to recognize phishing attempts, deploying anti-phishing software, and marking suspicious emails.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Suspicious activity monitoring: Continuously monitors for anomalies such as excessive email failures, unauthorized attempts to access user accounts, or unusual patterns in message content.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Website Security:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>SSL/TLS encryption: Encrypts all data transmitted between users and the platform to protect it from interception or tampering.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Domain authentication: Confirms that the website's domain matches its digital certificates to prevent man-in-the-middle attacks.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Regular security audits: Conducts periodic evaluations of website code, configurations, and infrastructure to detect vulnerabilities.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Malware scanning and prevention: Utilizes automated tools and real-time monitoring to identify and block malicious software from compromising the platform.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Reporting Mechanisms:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Dedicated fraud reporting channels: Provides secure and accessible means for users to report fraudulent activity or suspicious incidents.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Investigation procedures: Outlines structured steps for reviewing reported incidents, identifying root causes, and documenting findings.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Whistleblower protection: Ensures confidentiality and protection against retaliation for individuals who report fraud or security concerns.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Incident response protocols: Defines actions to take during fraud detection, including immediate containment, investigation, and resolution procedures.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">6.2 Access Control Systems</h4>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Authentication Protocols:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Multi-factor authentication (MFA): Requires users to verify their identity using multiple methods, such as passwords, biometric data, or one-time codes.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Biometric verification options: Includes fingerprint, facial recognition, or retina scans to ensure access security without relying solely on passwords.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Single sign-on (SSO) integration: Allows users to access multiple services with a single authentication process, improving convenience and security.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Password strength requirements: Enforces the use of complex passwords that meet predefined standards for length, character variety, and uniqueness.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Session Management:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Automatic session timeouts: Ends inactive sessions after a defined period to prevent unauthorized access.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Concurrent session controls: Restricts the number of active sessions a user can maintain to reduce the risk of account misuse.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>IP-based access restrictions: Limits access to specific IP ranges, reducing the likelihood of unauthorized logins.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Activity logging and monitoring: Records user actions within the system, enabling audit trails and detecting unusual behaviors.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">6.3 Data Integrity Measures</h4>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Validation Controls:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Input validation checks: Ensures all data entered into the system meets format and content expectations to prevent injection attacks or corrupt data.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Data consistency verification: Cross-references data across systems or processes to ensure accuracy and prevent discrepancies.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Automated error detection: Deploys algorithms that identify and flag errors for immediate correction or review.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Change tracking systems: Logs all modifications to data, including who made the change and when, for traceability and accountability.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Backup Procedures:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Regular data backups: Creates frequent copies of system data to ensure recoverability in case of loss or corruption.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Encrypted backup storage: Encrypts backup files to prevent unauthorized access even if storage systems are compromised.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Recovery testing protocols: Periodically tests backup restoration procedures to ensure reliability during real incidents.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Version control systems: Maintains historical versions of data and files, allowing for rollbacks to previous states when necessary.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">6.4 Incident Response</h4>
                                <ul class="list-unstyled">
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Detection Systems:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Real-time monitoring: Continuously observes system activities to detect and respond to threats as they occur.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Automated alert systems: Triggers notifications when predefined security thresholds are breached.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Behavioral analysis: Identifies unusual activity patterns that may indicate malicious behavior or breaches.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Threat intelligence integration: Uses external databases and feeds to stay updated on emerging threats and vulnerabilities.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Response Procedures:
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Incident classification protocols: Categorizes incidents based on severity and scope to prioritize response efforts.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Escalation procedures: Defines when and how to involve higher-level teams or external partners in incident resolution.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Communication plans: Establishes clear guidelines for internal and external communication during incidents, ensuring transparency.
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Recovery strategies: Outlines methods to restore systems and data to operational status while minimizing downtime.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </section>
                        </div>
                    </div>
                </div>

                <div class="tab-pane slide {{show-cookies}} {{active-cookies}}" id="cookies">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h2 class="mb-0">The Cookie Policy</h2>
                            <p class="mb-0">
                                <span class="text-green-200 fw-bold">(Version: 1.0.0)</span> Last Updated: {{last-update}}
                            </p>
                        </div>

                        <div class="card-body">

                            <section id="Introduction" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Introduction" title="Copy link to section"></i>
                                    <h3>1. Introduction</h3>
                                </div>

                                <p>This Cookie Policy explains how Last Hammer Framework and ADAH use cookies and similar technologies to recognize your activity and interpret your interaction with our platform. This document covers:</p>

                                <div class="mb-3">
                                    <p class="fw-bold">This Policy covers:</p>
                                    <ul class="list-unstyled">
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>What cookies are and how we use them:</b> An explanation of the nature of cookies and their specific uses.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Types of cookies we use:</b> A detailed description of the different categories of cookies and their functions.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Options for controlling cookies:</b> Tools and steps you can take to manage your cookie preferences.
                                        </li>
                                        <li class="ms-2 me-2">
                                            <i class="fas fa-check me-2"></i><b>Impact of cookie decisions:</b> How your choices regarding cookies may influence the functionality of our platform.
                                        </li>
                                    </ul>
                                </div>

                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Types-of-Cookies-We-Use" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Types-of-Cookies-We-Use" title="Copy link to section"></i>
                                    <h3>2. Types of Cookies We Use</h3>
                                </div>

                                <h4 class="ms-1 mb-1">2.1 Essential Cookies</h4>
                                <p class="ms-1 mb-1">These cookies are fundamental to ensuring that our platform operates correctly and to maintaining your security while browsing.</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Authentication cookies: Validate your identity when logging in.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Session management: Preserve information about your session state, enabling a continuous experience
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Security tokens: Protect your account from unauthorized access.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Login state maintenance: Ensure you do not need to log in repeatedly during platform use.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Security cookies: Block malicious activities.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Fraud prevention: Detect and prevent attempts of fraudulent activities.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>CSRF (Cross-Site Request Forgery) protection: Safeguard your data from unauthorized requests from other sites.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Attack prevention: Mitigate risks associated with hacking attempts and other cyberattacks.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">2.2 Functional Cookies</h4>
                                <p class="ms-1 mb-1">These cookies enhance your experience by providing personalized options tailored to your needs.</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Preference cookies: Store your language settings and preferences.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Language settings: Ensure content is displayed in your preferred language.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Theme preferences: Allow the platform to remember your choice between light and dark mode.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Interface customization: Adjust the platform layout based on your selections.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Feature cookies: Offer functionalities such as autofill in forms and customized settings.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Form autofill: Store information you have previously entered.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Search history: Facilitate quick access to previous searches.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Dashboard settings: Remember your configuration settings within the platform.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1 mb-1">2.3 Performance Cookies</h4>
                                <p class="ms-1 mb-1">These cookies collect data to assess platform performance and improve efficiency and stability.</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Analytics cookies: Track general platform usage to understand browsing patterns.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Usage patterns: Identify how users interact with different areas of the platform.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Error tracking: Help identify and correct technical issues.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Performance metrics: Measure loading speed and system behavior.
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Diagnostic cookies: Assist in identifying specific issues related to the infrastructure.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Load balancing: Distribute server requests to maintain platform speed and stability.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Response times: Monitor how quickly the platform responds to your requests.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>System health: Evaluate the overall status of our infrastructure to ensure smooth operation.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <section id="Managing-Your-Cookie-Preferences" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Managing-Your-Cookie-Preferences" title="Copy link to section"></i>
                                    <h3>3. Managing Your Cookie Preferences</h3>
                                </div>

                                <h4 class="ms-1">3.1 Browser Controls</h4>
                                <p class="ms-1 mb-1">You can manage cookies directly from your browser using the following options:</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Browser settings: Access settings to enable or disable cookies.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Cookie blocking: Restrict specific or all cookies depending on your needs.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Cookie deletion: Delete existing cookies to reset preferences or improve privacy.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Private browsing: Use this option to prevent cookies from being saved when closing the browser.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1">3.2 Platform Controls</h4>
                                <p class="ms-1 mb-1">Our platform also provides built-in tools to manage your cookie preferences:</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Cookie preferences: Adjust settings directly from the control panel.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Preference center: Centralize all cookie management options.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Consent manager: Provide specific controls to allow or reject cookies.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Category selection: Enable or disable cookies by type (essential, functional, performance, etc.).
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </section>

                            <div class="text-success">
                                <hr>
                            </div>

                            <!-- Impact of Choices Section -->
                            <section id="Impact-of-Cookie-Choices" class="mb-4">

                                <div class="section-heading">
                                    <i class="fas fa-link section-link" data-section="Impact-of-Cookie-Choices" title="Copy link to section"></i>
                                    <h3>4. Impact of Cookie Choices</h3>
                                </div>

                                <h4 class="ms-1">4.1 Essential Functionality</h4>
                                <p class="ms-1 mb-1">If you decide to disable essential cookies, you may experience issues with:</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Core features: Some parts of the platform may not function as expected
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Authentication systems: You may face difficulties logging in.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Security measures: The platform may become more vulnerable to attacks.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Basic navigation: You may encounter problems with session stability and continuity.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <h4 class="ms-1">4.2 Optional Features</h4>
                                <p class="ms-1 mb-1">Disabling functional or performance cookies may affect:</p>
                                <ul class="list-unstyled mb-1">
                                    <li class="ms-2 me-2">
                                        <i class="fas fa-circle me-2"></i>Enhanced functionality: Features like personalization and tailored suggestions.
                                        <ul class="list-unstyled mb-1">
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Personalization: Your preferences and personal settings will not be remembered.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fa-regular fa-circle me-2"></i>Analytics: Data used to improve the platform will be less accurate.
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                            </section>


                        </div>
                    </div>
                </div>

                <div class="tab-pane slide {{show-humanitarian}} {{active-humanitarian}}" id="humanitarian">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h2 class="mb-0">The Humanitarian Data Framework</h2>
                            <p class="mb-0">
                                <span class="text-green-200 fw-bold">(Version: 1.0.0)</span> Last Updated: {{last-update}}
                            </p>
                        </div>
                        <div class="card-body">
                            <div class="humanitarian-content">

                                <section id="Introduction" class="mb-4">

                                    <div class="section-heading">
                                        <i class="fas fa-link section-link" data-section="Introduction" title="Copy link to section"></i>
                                        <h3>1. Introduction</h3>
                                    </div>

                                    <p>The Humanitarian Data Framework (Version 1.0.0) establishes a robust foundation for ethical and secure data management in humanitarian operations. This document ensures that all data handling within the Last Hammer Framework and ADAH adheres to global humanitarian standards, with an unwavering focus on safeguarding vulnerable populations.</p>

                                    <div class="mb-3">
                                        <p class="fw-bold">This framework includes:</p>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-check me-2"></i><b>Core principles and standards</b>
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-check me-2"></i><b>Operational guidelines focused on humanitarian efforts</b>
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-check me-2"></i><b>Compliance requirements tailored to humanitarian contexts</b>
                                            </li>
                                        </ul>
                                    </div>

                                </section>

                                <div class="text-success">
                                    <hr>
                                </div>

                                <section id="Core-Principles" class="mb-4">

                                    <div class="section-heading">
                                        <i class="fas fa-link section-link" data-section="Core-Principles" title="Copy link to section"></i>
                                        <h3>2. Core Principles</h3>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">2.1 Data Protection in Humanitarian Contexts</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Security Measures
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Focus on protecting sensitive humanitarian data in conflict zones and disaster-prone areas.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Implement encryption specifically for field communication devices.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Ensure secure storage and rapid recovery of critical beneficiary data during emergencies.
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Data Handling in Emergencies
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Prioritize secure and efficient data transfer during crisis scenarios.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Maintain protocols for safeguarding data integrity under high-pressure situations.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">2.1 Informed Consent</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Consent for Humanitarian Use
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Provide clear, context-specific explanations for data collection purposes.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Adapt consent mechanisms to account for cultural and linguistic variations in affected areas.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">2.3 Data Minimization in Humanitarian Activities</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Collection Policies
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Gather only the data necessary for delivering immediate aid and long-term support.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Avoid storing personal data beyond the scope of humanitarian objectives.
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Field Applications
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Optimize data collection processes for on-the-ground humanitarian teams.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">2.4 Purpose Limitation</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Humanitarian Focus
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Limit data usage strictly to humanitarian aid delivery, reporting, and compliance.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Conduct regular impact assessments to avoid unintended consequences.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">2.5 Data Quality</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Quality Assurance
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Emphasize data accuracy for beneficiary tracking and resource allocation.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Regularly validate and update field data to maintain its relevance.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">2.6 Accountability and Reporting</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Humanitarian-Specific Transparency
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Establish reporting systems tailored to donors, beneficiaries, and stakeholders in humanitarian contexts.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Ensure public access to impact reports for enhanced trust.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </section>

                                <div class="text-success">
                                    <hr>
                                </div>

                                <section id="International-Standards-Compliance" class="mb-4">

                                    <div class="section-heading">
                                        <i class="fas fa-link section-link" data-section="International-Standards-Compliance" title="Copy link to section"></i>
                                        <h3>3. International Standards Compliance</h3>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">3.1 International Humanitarian Law</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-3 me-2">
                                                <i class="fas fa-circle me-2"></i>Integrate civilian data protection principles into humanitarian operations.
                                            </li>
                                            <li class="ms-3 me-2">
                                                <i class="fas fa-circle me-2"></i>Enhance safeguards for vulnerable groups like displaced populations and children.
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">3.2 OCHA Guidelines</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Data Responsibility in Crises
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Align data handling practices with OCHA’s humanitarian action principles.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">3.3 HXL Standards</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Data Standardization for Aid and Mission
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Utilize HXL tags to streamline data sharing among humanitarian organizations.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">3.4 CHS Accountability</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Community Engagement
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Develop participatory mechanisms to engage local communities in decision-making processes.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </section>

                                <div class="text-success">
                                    <hr>
                                </div>

                                <section id="Humanitarian-Operations" class="mb-4">

                                    <div class="section-heading">
                                        <i class="fas fa-link section-link" data-section="Humanitarian-Operations" title="Copy link to section"></i>
                                        <h3>4. Humanitarian Operations</h3>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">4.1 Community Support</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Assessment and Tracking Tools
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Deploy tools to evaluate needs and track the effectiveness of delivered aid.
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Resource Management
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Monitor the allocation and distribution of humanitarian resources to ensure equitable access.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">4.2 Volunteer Coordination</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Training and Deployment
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Equip volunteers with the necessary training for effective field operations.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Implement systems for tracking volunteer roles and contributions.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">4.4 Emergency Response</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Rapid Response
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Deployment protocols
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Resource mobilization
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Emergency coordination
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Communication Systems
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Real-time updates
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Team coordination
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Status reporting
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                </section>

                                <div class="text-success">
                                    <hr>
                                </div>

                                <section class="mb-4">

                                    <div id="Ethical-Framework-Implementation" class="section-heading">
                                        <i class="fas fa-link section-link" data-section="Ethical-Framework-Implementation" title="Copy link to section"></i>
                                        <h3>4. Ethical Framework Implementation</h3>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">5.1 Humanitarian Principles</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2">
                                                <i class="fas fa-circle me-2"></i>Core Values
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Uphold humanity, neutrality, and impartiality in all data-related operations.
                                                    </li>
                                                </ul>
                                            </li>
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Cultural Adaptation
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Ensure respect for local customs and practices during data collection and analysis.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="mb-3">
                                        <h4 class="ms-1">5.2 Language and Accessibility</h4>
                                        <ul class="list-unstyled">
                                            <li class="ms-2 me-2"><i class="fas fa-circle me-2"></i>Multilingual Support
                                                <ul class="list-unstyled">
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Provide multilingual tools and services for affected populations.
                                                    </li>
                                                    <li class="ms-3 me-2">
                                                        <i class="fa-regular fa-circle me-2"></i>Facilitate communication with beneficiaries in their native languages.
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <!-- Agreement Section -->
            <!--
            <div class="card mt-4">
                <div class="card-body text-center">
                    <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" id="acceptAll">
                        <label class="form-check-label" for="acceptAll">
                            I have read and agree to all terms, policies, and conditions
                        </label>
                    </div>
                    <div class="btn-group">
                        <button class="btn btn-primary" id="acceptButton" disabled>Accept All</button>
                        <a href="/" class="btn btn-secondary">Decline</a>
                    </div>
                </div>
            </div>
            -->
        </div>
    </div>
</div>