<div id="app" class="app app-header-fixed app-sidebar-fixed app-content-full-height">

    <div id="header" class="app-header">

        <div class="navbar-header">
            <a href="#dashboard-1" class="navbar-brand">
                <img src="assets/img/ico/64.png" alt="Brand Image"/> <b class="me-3px"> ADAH </b>
            </a>
            <button type="button" class="navbar-mobile-toggler" data-toggle="app-sidebar-mobile">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>


        <div class="navbar-nav">
            <div class="navbar-item navbar-form">
                <form action method="POST" name="search">
                    <div class="form-group">
                        <label for="search">
                            <input id="search" type="text" class="form-control" placeholder="Buscar Voluntario"/>
                        </label>
                        <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
            <div class="navbar-item dropdown">
                <a href="#" data-bs-toggle="dropdown" class="navbar-link dropdown-toggle icon">
                    <i class="fa fa-bell"></i>
                    <span class="badge">5</span>
                </a>
                <div class="dropdown-menu media-list dropdown-menu-end">
                    <div class="dropdown-header">NOTIFICATIONS (5)</div>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <i class="fa fa-bug media-object bg-gray-500"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">Server Error Reports
                                <i class="fa fa-exclamation-circle text-danger"></i>
                            </h6>
                            <div class="text-muted fs-10px">3 minutes ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <img src="assets/img/user/user-1.jpg" class="media-object" alt/>
                            <i class="fab fa-facebook-messenger text-blue media-object-icon"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">John Smith</h6>
                            <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                            <div class="text-muted fs-10px">25 minutes ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <img src="assets/img/user/user-2.jpg" class="media-object" alt/>
                            <i class="fab fa-facebook-messenger text-blue media-object-icon"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">Olivia</h6>
                            <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                            <div class="text-muted fs-10px">35 minutes ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <i class="fa fa-plus media-object bg-gray-500"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"> New User Registered</h6>
                            <div class="text-muted fs-10px">1 hour ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <i class="fa fa-envelope media-object bg-gray-500"></i>
                            <i class="fab fa-google text-warning media-object-icon fs-14px"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"> New Email From John</h6>
                            <div class="text-muted fs-10px">2 hour ago</div>
                        </div>
                    </a>
                    <div class="dropdown-footer text-center">
                        <a href="#" class="text-decoration-none">View more</a>
                    </div>
                </div>
            </div>
            <div class="navbar-item navbar-user dropdown">
                <a href="#" class="navbar-link dropdown-toggle d-flex align-items-center" data-bs-toggle="dropdown">
                    <img src="assets/img/user/user-13.jpg" alt/>
                    <span>
                        <span class="d-none d-md-inline">Walter Nuñez</span>
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-end me-1">
                    <a href="#extra_profile" class="dropdown-item">Edit Profile</a>
                    <a href="#email_inbox" class="dropdown-item d-flex align-items-center">
                        Inbox
                        <span class="badge bg-danger rounded-pill ms-auto pb-4px">2</span>
                    </a>
                    <a href="#calendar" class="dropdown-item">Calendar</a>
                    <a href="#extra_settings_pagel" class="dropdown-item">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a href="#login" class="dropdown-item">Log Out</a>
                </div>
            </div>
        </div>

    </div>


    <div id="sidebar" class="app-sidebar" data-bs-theme="dark">

        <div class="app-sidebar-content" data-scrollbar="true" data-height="100%">

            <div class="menu">
                <div class="menu-profile">
                    <a href="#" class="menu-profile-link" data-toggle="app-sidebar-profile"
                       data-target="#appSidebarProfileMenu">
                        <div class="menu-profile-cover with-shadow"></div>
                        <div class="menu-profile-image">
                            <img src="assets/img/user/user-13.jpg" alt/>
                        </div>
                        <div class="menu-profile-info">
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1">Walter Nuñez</div>
                                <div class="menu-caret ms-auto"></div>
                            </div>
                            <small>Ing. Sistemas</small>
                        </div>
                    </a>
                </div>
                <div id="appSidebarProfileMenu" class="collapse">
                    <div class="menu-item pt-5px">
                        <a href="#" class="menu-link">
                            <div class="menu-icon"><i class="fa fa-cog"></i></div>
                            <div class="menu-text">Configurar Cuenta</div>
                        </a>
                    </div>
                    <div class="menu-item">
                        <a href="#" class="menu-link">
                            <div class="menu-icon"><i class="fa fa-pencil-alt"></i></div>
                            <div class="menu-text"> Enviar Reporte</div>
                        </a>
                    </div>
                    <div class="menu-item pb-5px">
                        <a href="#" class="menu-link">
                            <div class="menu-icon"><i class="fa fa-question-circle"></i></div>
                            <div class="menu-text"> Ayudas</div>
                        </a>
                    </div>
                    <div class="menu-divider m-0"></div>
                </div>
                <div class="menu-header">Menu</div>
                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Mantenimiento</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Mantenimiento 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Mantenimiento 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Mantenimiento 3</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Procesos</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item ">
                            <a href="/Calendar" class="menu-link">
                                <div class="menu-text">Calendario y Eventos</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Procesos 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Procesos 3</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Aprobaciones</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item active">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Aprobación 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Aprobación 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Aprobación 3</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Reportes</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item active">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Reporte 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Reporte 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Reporte 3</div>
                            </a>
                        </div>
                    </div>
                </div>


                <div class="menu-item d-flex">
                    <a href="#"
                       class="app-sidebar-minify-btn ms-auto d-flex align-items-center text-decoration-none"
                       data-toggle="app-sidebar-minify">
                        <i class="fa fa-angle-double-left"></i>
                    </a>
                </div>

            </div>

        </div>

    </div>

    <div class="app-sidebar-bg" data-bs-theme="dark"></div>

    <div class="app-sidebar-mobile-backdrop">
        <a href="#" data-dismiss="app-sidebar-mobile" class="stretched-link"></a>
    </div>


    <div id="content" class="app-content d-flex flex-column p-0">

        <div class="app-content-padding flex-grow-1 overflow-hidden" data-scrollbar="true" data-height="100%">

            <ol class="breadcrumb float-xl-end">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>

            <h1 class="page-header" id="dashboard-1">Dashboard #1 <small>header small text goes here...</small></h1>

            <div class="panel panel-inverse">

                <div class="panel-heading">
                    <h4 class="panel-title">Perfiles de Voluntario</h4>
                    <div class="panel-heading-btn">
                        <a href="#" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                                    class="fa fa-expand"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                                    class="fa fa-redo"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i
                                    class="fa fa-minus"></i></a>
                        <a href="#" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i
                                    class="fa fa-times"></i></a>
                    </div>
                </div>


                <div class="panel-body">

                    <div class="table-responsive">
                        <table class="table table-striped mb-0 align-middle">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Cédula</th>
                                <th>Base</th>
                                <th>Email Address</th>
                                <th>Teléfono</th>
                                <th width="1%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-1.jpg" class="rounded h-30px">
                                </td>
                                <td>Allan Fuentes</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <a href="#modal-fuentes" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>

                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-2.jpg" class="rounded h-30px">
                                </td>
                                <td>Allan Pitty</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <a href="#modal-pitty" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>
                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-3.jpg" class="rounded h-30px">
                                </td>
                                <td>Walter Nuñez</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end" z-index="9999">
                                            <a href="#modal-nunez" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>
                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-1.jpg" class="rounded h-30px">
                                </td>
                                <td>Allan Fuentes</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <a href="#modal-fuentes" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>

                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-2.jpg" class="rounded h-30px">
                                </td>
                                <td>Allan Pitty</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <a href="#modal-pitty" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>
                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-3.jpg" class="rounded h-30px">
                                </td>
                                <td>Walter Nuñez</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end" z-index="9999">
                                            <a href="#modal-nunez" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>
                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-1.jpg" class="rounded h-30px">
                                </td>
                                <td>Allan Fuentes</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <a href="#modal-fuentes" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>

                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-2.jpg" class="rounded h-30px">
                                </td>
                                <td>Allan Pitty</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end">
                                            <a href="#modal-pitty" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>
                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <img src="../assets/img/user/user-3.jpg" class="rounded h-30px">
                                </td>
                                <td>Walter Nuñez</td>

                                <td>1-123-345</td>
                                <td>Base Omega</td>

                                <td>correo@electronico.com</td>
                                <td>66996699</td>
                                <td nowrap="">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-white btn-sm w-90px">Ver</a>
                                        <a href="#" class="btn btn-white btn-sm dropdown-toggle w-30px no-caret"
                                           data-bs-toggle="dropdown">
                                            <span class="caret"></span>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-end" z-index="9999">
                                            <a href="#modal-nunez" data-bs-toggle="modal"
                                               class="dropdown-item">Perfil</a>
                                            <a href="#" class="dropdown-item">Permisos</a>
                                            <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item">Action 3</a>
                                            <a href="#" class="dropdown-item">Action 4</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                </div>


                <div class="modal fade" id="modal-fuentes">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Perfil de Voluntario</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="assets/img/user/user-11.jpg" alt="Foto de perfil"
                                             class="img-fluid rounded-circle mb-3">
                                    </div>
                                    <div class="col-md-8">
                                        <h3>Allan Fuentes</h3>
                                        <p><strong>Correo:</strong> correo@ejemplo.com</p>
                                        <p><strong>Teléfono:</strong> +1234567890</p>
                                        <p><strong>Ubicación:</strong> Ciudad, País</p>
                                    </div>
                                </div>
                                <hr>
                                <h4>Estudios y Cursos</h4>
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <h5>Grado en Ingeniería Informática</h5>
                                        <p>Universidad XYZ, 2015-2019</p>
                                    </li>
                                    <li class="list-group-item">
                                        <h5>Máster en Inteligencia Artificial</h5>
                                        <p>Instituto ABC, 2020-2021</p>
                                    </li>
                                    <li class="list-group-item">
                                        <h5>Curso de Desarrollo Web Full Stack</h5>
                                        <p>Plataforma Online DEF, 2022</p>
                                    </li>
                                </ul>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-company-name" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="modal fade" id="modal-pitty">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Perfil de Voluntario</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">

                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="assets/img/user/user-12.jpg" alt="Foto de perfil"
                                             class="img-fluid rounded-circle mb-3">
                                    </div>
                                    <div class="col-md-8">
                                        <h3>Allan Pitty</h3>
                                        <p><strong>Correo:</strong> correo@ejemplo.com</p>
                                        <p><strong>Teléfono:</strong> +1234567890</p>
                                        <p><strong>Ubicación:</strong> Ciudad, País</p>
                                    </div>
                                </div>
                                <hr>
                                <h4>Estudios y Cursos</h4>
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <h5>Grado en Ingeniería Informática</h5>
                                        <p>Universidad XYZ, 2015-2019</p>
                                    </li>
                                    <li class="list-group-item">
                                        <h5>Máster en Inteligencia Artificial</h5>
                                        <p>Instituto ABC, 2020-2021</p>
                                    </li>
                                    <li class="list-group-item">
                                        <h5>Curso de Desarrollo Web Full Stack</h5>
                                        <p>Plataforma Online DEF, 2022</p>
                                    </li>
                                </ul>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-company-name" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="modal fade" id="modal-nunez">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Perfil de Voluntario</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img src="assets/img/user/user-14.jpg" alt="Foto de perfil"
                                             class="img-fluid rounded-circle mb-3">
                                    </div>
                                    <div class="col-md-8">
                                        <h3>Walter Nunez</h3>
                                        <p><strong>Correo:</strong> correo@ejemplo.com</p>
                                        <p><strong>Teléfono:</strong> +1234567890</p>
                                        <p><strong>Ubicación:</strong> Ciudad, País</p>
                                    </div>
                                </div>
                                <div class="mt-3 mb-3">
                                    <h4>Áreas de especialización</h4>
                                    <button type="button" class="btn btn-outline-primary btn-sm me-2 mb-2">Telemática
                                    </button>
                                    <button type="button" class="btn btn-outline-secondary btn-sm me-2 mb-2">
                                        Telecomunicaciones
                                    </button>
                                    <button type="button" class="btn btn-outline-success btn-sm me-2 mb-2">Informática
                                    </button>
                                    <button type="button" class="btn btn-outline-info btn-sm me-2 mb-2">Redes</button>
                                    <button type="button" class="btn btn-outline-warning btn-sm me-2 mb-2">
                                        Programación
                                    </button>
                                </div>
                                <hr>
                                <div class="mt-3 mb-3">
                                    <h4>Reconocimientos</h4>
                                    <div class="d-flex flex-wrap align-items-center">
                                        <div class="medal-container">
                                            <div class="medal gold">
                                                <span class="medal-ribbon"></span>
                                            </div>
                                            <span class="medal-tooltip">Medalla de Honor al Mérito</span>
                                        </div>
                                        <div class="medal-container">
                                            <div class="medal silver">
                                                <span class="medal-ribbon"></span>
                                            </div>
                                            <span class="medal-tooltip">Medalla por Actos Heroicos</span>
                                        </div>
                                        <div class="medal-container">
                                            <div class="medal bronze">
                                                <span class="medal-ribbon"></span>
                                            </div>
                                            <span class="medal-tooltip">Medalla de Servicio Distinguido</span>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <h4>Estudios y Cursos</h4>
                                <ul class="list-group">
                                    <li class="list-group-item">
                                        <h5>Grado en Ingeniería Informática</h5>
                                        <p>Universidad XYZ, 2015-2019</p>
                                    </li>
                                    <li class="list-group-item">
                                        <h5>Máster en Inteligencia Artificial</h5>
                                        <p>Instituto ABC, 2020-2021</p>
                                    </li>
                                    <li class="list-group-item">
                                        <h5>Curso de Desarrollo Web Full Stack</h5>
                                        <p>Plataforma Online DEF, 2022</p>
                                    </li>
                                </ul>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-company-name" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="hljs-wrapper">
                    <pre><code class="html" data-url="../assets/data/table-manage/default.json"></code></pre>
                </div>

            </div>

        </div>

        <div id="footer" class="app-footer m-0">
            &copy; 2024 Icaros Net | Last Hammer Framework | ADAH - All Rights Reserved
            <span class="pull-right">
                <a href="#" class="btn-scroll-to-top" data-click="scroll-top">
                    <i class="fa fa-arrow-up"></i> <span class="hidden-xs">Back to Top</span>
                </a>
            </span>
        </div>

    </div>


    {{app_setting}}


    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top fixed-footer" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>

</div>