<div class="container flex-container mt-3 text-center placeholder-glow" style="max-width: 330px">
    <img class="mb-4" src="assets/ico/128.png" alt="" width="128" height="128">
    <nav class="nav nav-fill nav-tabs" role="tablist">
        <a class="nav-link fw-bold fs-4 col-6 {{form_login}}" id="login-tab" data-bs-toggle="tab" data-bs-target="#login-tab-pane" type="button" role="tab" aria-controls="login-tab-pane"
           aria-selected="true">Sign In</a>
        <a class="nav-link fw-bold fs-4 col-6 {{form_register}}" id="register-tab" data-bs-toggle="tab" data-bs-target="#register-tab-pane" type="button" role="tab" aria-controls="register-tab-pane"
           aria-selected="true">Sign Up</a>
    </nav>
    <div class="tab-content" id="accessTabContent">
        <div class="tab-pane fade {{form_login_show}} {{form_login}}" id="login-tab-pane" role="tabpanel" aria-labelledby="login-tab" tabindex="0">
            <form class="mt-1" method="post" action="/useraccess">
                <div class="row mt-2">
                    <div class="col-12">
                        {{success_login}}
                        {{error_email_l}}
                        <label for="l-email" class="form-label visually-hidden">Email</label>
                        <input type="email" class="form-control form-control-lg" id="l-email" name="l-email" placeholder="name@example.com" value="{{l-email}}" required>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        {{error_password_l}}
                        <label for="l-password" class="form-label visually-hidden">Password</label>

                        <div class="input-group">
                            <input type="password" class="form-control form-control-lg" id="l-password" name="l-password" placeholder="********" value="{{l-password}}" required>
                            <button class="btn btn-success view-password" type="button" data-target="l-password"><i class="fa-solid fa-eye"></i></button>
                        </div>

                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12 fst-italic text-end" style="font-size: 11px">
                        <a class="text-decoration-underline text-warning" data-bs-toggle="modal" data-bs-target="#restore-password">Forgot Password?</a>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div class="form-check form-switch ms-5 text-start">
                            <input class="form-check-input switch-lg me-2" type="checkbox" role="switch" id="remember" name="remember" {{remember}}>
                            <label class="form-check-label" for="remember">Remember Account</label>
                        </div>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <button class="w-100 btn btn-lg btn-primary fw-bold" type="submit" name="event" value="login">Sign In</button>
                    </div>
                </div>
                <!--
                <div class="row mt-2">
                    <div class="col-12">
                        <label>or</label>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <button class="w-100 btn btn-outline-light btn-lg fw-bold border" style="color:#DB4437" type="submit">Sign In with <i class="fa-brands fa-google"></i></button>
                    </div>
                </div>
                -->
            </form>
        </div>
        <div class="tab-pane fade {{form_register_show}} {{form_register}}" id="register-tab-pane" role="tabpanel" aria-labelledby="register-tab" tabindex="0">
            <form class="mt-1" method="post" action="/useraccess">
                <div class="row mt-2">
                    <div class="col-12">
                        {{success_register}}
                        {{error_email_r}}
                        <label for="r-email" class="form-label visually-hidden">Email</label>
                        <input type="email" class="form-control form-control-lg" id="r-email" name="r-email" placeholder="name@example.com" value="{{r-email}}" required>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        {{error_password_r}}
                        <label for="r-password" class="form-label visually-hidden">Password</label>
                        <div class="input-group">
                            <input type="password" class="form-control form-control-lg" id="r-password" name="r-password" placeholder="Password" value="{{r-password}}" required>
                            <button class="btn btn-success view-password" type="button" data-target="r-password"><i class="fa-solid fa-eye"></i></button>
                        </div>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        {{error_password_r_rep}}
                        <label for="r-password-rep" class="form-label visually-hidden">Repite-Password</label>
                        <div class="input-group">
                            <input type="password" class="form-control form-control-lg" id="r-password-rep" name="r-password-rep" placeholder="Repeat Password" value="{{r-password-rep}}" required>
                            <button class="btn btn-success view-password" type="button" data-target="r-password-rep"><i class="fa-solid fa-eye"></i></button>
                        </div>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <label class="form-label text-danger fst-italic" style="font-size: 0.75rem" for="remember">By registering on this website you are accepting the
                            <a class="text-decoration-underline" data-bs-toggle="modal" data-bs-target="#term-of-service">Terms of Service</a> and
                            <a class="text-decoration-underline" data-bs-toggle="modal" data-bs-target="#privacy-policies">Privacy Policies</a>:</label>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div class="form-check form-switch d-flex justify-content-center">
                            <input class="form-check-input switch-lg" type="checkbox" role="switch" id="approve" name="approve" required {{approve}}>
                        </div>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12 ">
                        <button class="w-100 btn btn-lg btn-primary fw-bold" type="submit" name="event" value="register">Sign Up</button>
                    </div>
                </div>
                <!--
                <div class="row mt-2">
                    <div class="col-12">
                        <label>or</label>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <button class="w-100 btn btn-outline-light btn-lg fw-bold border" style="color:#DB4437" type="submit">Sign Up with <i class="fa-brands fa-google"></i></button>
                    </div>
                </div>
                -->
            </form>
        </div>
    </div>
</div>
<footer class="footer mt-auto py-1 bg-primary bg-gradient fixed-bottom">
    <div class="container-fluid ps-0 pe-0">
        <div class="input-group custom-font text-center">
            <a class="text-decoration-none border-0 m-auto bg-primary bg-gradient text-white" href="/contact">All Rights Reserved. &trade; TCG-Wallet &reg; Contact Us</a>
        </div>
    </div>
</footer>
<div class="modal fade" id="restore-password" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="/useraccess">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Restore Password</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            {{success_recovery}}
                            {{error_recovery}}
                            <label for="rec-email" class="form-label visually-hidden">Email</label>
                            <input type="email" class="form-control form-control-lg" id="rec-email" name="rec-email" placeholder="name@example.com" value="{{rec-email}}" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-warning" data-bs-dismiss="modal" name="event" value="recovery">Request Restore</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="term-of-service" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Terms of Service</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{term-of-service}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="privacy-policies" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Privacy Policies</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {{privacy-policies}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
