<div class="container flex-container mt-3 text-center placeholder-glow" style="max-width: 330px">
    {{a-redirect}}
    <img class="mb-4" src="assets/ico/128.png" alt="" width="128" height="128">
    <nav class="nav nav-fill nav-tabs" role="tablist">
        <a class="nav-link fw-bold fs-4 col-6 {{form_login}}" id="login-tab" data-bs-toggle="tab" data-bs-target="#login-tab-pane" type="button" role="tab" aria-controls="login-tab-pane"
           aria-selected="true">Activation Account</a>
    </nav>
    <div class="tab-content" id="accessTabContent">
        <div class="tab-pane fade {{form_login_show}} {{form_login}}" id="login-tab-pane" role="tabpanel" aria-labelledby="login-tab" tabindex="0">
            <form class="mt-1" method="post" action="/useractivation">

                <div class="row mt-2">
                    <div class="col-12">
                        {{success_activation}}
                        {{error_email_a}}
                        <label for="a-email" class="form-label visually-hidden">Email</label>
                        <input type="email" class="form-control form-control-lg" id="a-email" name="a-email" placeholder="name@example.com" value="{{a-email}}" required>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        {{error_token_a}}
                        <label for="a-token" class="form-label visually-hidden">Token</label>
                        <input type="text" class="form-control form-control-lg" id="a-token" name="a-token" value="{{a-token}}" required readonly>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12 ">
                        <button class="w-100 btn btn-lg btn-primary fw-bold" type="submit" name="event" value="activate">Activate</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
