<div id="app" class="app">

    <div class="error">
        <div class="error-code">404</div>
        <div class="error-content">
            <div class="error-message">Não conseguimos encontrar...</div>
            <div class="error-desc mb-4">
                A página que você está procurando não existe. <br/>
                Talvez essas páginas ajudem você a encontrar o que procura.
            </div>
            <div>
                <a href="/User-Access" class="btn btn-success px-3">Volte para casa.</a>
            </div>
        </div>
    </div>
    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>