<div id="app" class="app">

    <div class="error">
        <div class="error-code">404</div>
        <div class="error-content">
            <div class="error-message">Nous n'avons pas pu le trouver...</div>
            <div class="error-desc mb-4">
                La page que vous recherchez n'existe pas. <br/>
                Peut-être que ces pages vous aideront à trouver ce que vous cherchez.
            </div>
            <div>
                <a href="/{{sys-home}}" class="btn btn-success px-3">Allez à Accueil.</a>
            </div>
        </div>
    </div>
    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>