<div id="app" class="app">

    <div class="error">
        <div class="error-code">404</div>
        <div class="error-content">
            <div class="error-message">No pudimos encontrarlo...</div>
            <div class="error-desc mb-4">
                La página que estás buscando no existe. <br/>
                Quizás estas páginas te ayudarán a encontrar lo que estás buscando.
            </div>
            <div>
                <a href="/{{sys-home}}" class="btn btn-success px-3">Ir al inicio</a>
            </div>
        </div>
    </div>
    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>