<div class="fst-italic fw-light m-2 placeholder-glow" style="font-size: 9px">
    PRIVACY POLICY

    We want you to understand the types of information we collect as you use our services

    We collect information to provide better services to all our users — from figuring out basic stuff like which language you speak, to more complex things like which ads you’ll find most useful, the
    people who matter most to you online, or which YouTube videos you might like. The information TCG-Wallet collects, and how that information is used, depends on how you use our services and how you
    manage your privacy controls.

    When you’re not signed in to a TCG-Wallet Account, we store the information we collect with unique identifiers tied to the browser, application, or device you’re using. This allows us to do things
    like maintain your preferences across browsing sessions, such as your preferred language or whether to show you more relevant search results or ads based on your activity.

    When you’re signed in, we also collect information that we store with your TCG-Wallet Account, which we treat as personal information.


    Things you create or provide to us


    When you create a TCG-Wallet Account, you provide us with personal information that includes your name and a password. You can also choose to add a phone number or payment information to your
    account. Even if you aren’t signed in to a TCG-Wallet Account, you might choose to provide us with information — like an email address to communicate with TCG-Wallet or receive updates about our
    services.

    We also collect the content you create, upload, or receive from others when using our services. This includes things like email you write and receive, photos and videos you save, docs and
    spreadsheets you create, and comments you make on YouTube videos.


    Information we collect as you use our services

    Your apps, browsers & devices

    We collect information about the apps, browsers, and devices you use to access TCG-Wallet services, which helps us provide features like automatic product updates and dimming your screen if your
    battery runs low.

    The information we collect includes unique identifiers, browser type and settings, device type and settings, operating system, mobile network information including carrier name and phone number,
    and application version number. We also collect information about the interaction of your apps, browsers, and devices with our services, including IP address, crash reports, system activity, and
    the date, time, and referrer URL of your request.

    We collect this information when a TCG-Wallet service on your device contacts our servers — for example, when you install an app from the Play Store or when a service checks for automatic updates.
    If you’re using an Android device with TCG-Wallet apps, your device periodically contacts TCG-Wallet servers to provide information about your device and connection to our services. This
    information includes things like your device type and carrier name, crash reports, which apps you've installed, and, depending on your device settings, other information about how you’re using
    your Android device.

    Your activity

    We collect information about your activity in our services, which we use to do things like recommend a YouTube video you might like. The activity information we collect may include:

    Terms you search for
    Videos you watch
    Views and interactions with content and ads
    Voice and audio information
    Purchase activity
    People with whom you communicate or share content
    Activity on third-party sites and apps that use our services
    Chrome browsing history you’ve synced with your TCG-Wallet Account
    If you use our services to make and receive calls or send and receive messages, we may collect call and message log information like your phone number, calling-party number, receiving-party
    number, forwarding numbers, sender and recipient email address, time and date of calls and messages, duration of calls, routing information, and types and volumes of calls and messages.

    You can visit your TCG-Wallet Account to find and manage activity information that’s saved in your account.

    Your location information

    We collect information about your location when you use our services, which helps us offer features like driving directions, search results for things near you, and ads based on your general
    location.

    Your location can be determined with varying degrees of accuracy by:

    GPS and other sensor data from your device
    IP address
    Activity on TCG-Wallet services, such as your searches and places you label like home or work
    Information about things near your device, such as Wi-Fi access points, cell towers, and Bluetooth-enabled devices
    The types of location data we collect and how long we store it depend in part on your device and account settings. For example, you can turn your Android device’s location on or off using the
    device’s settings app. You can also turn on Location History if you want to create a private map of where you go with your signed-in devices. And if your Web & App Activity setting is enabled,
    your searches and other activity from TCG-Wallet services, which may also include location information, is saved to your TCG-Wallet Account. Learn more about how we use location information.

    In some circumstances, TCG-Wallet also collects information about you from publicly accessible sources. For example, if your name appears in your local newspaper, TCG-Wallet’s Search engine may
    index that article and display it to other people if they search for your name. We may also collect information about you from trusted partners, such as directory services who provide us with
    business information to be displayed on TCG-Wallet’s services, marketing partners who provide us with information about potential customers of our business services, and security partners who
    provide us with information to protect against abuse. We also receive information from advertising partners to provide advertising and research services on their behalf.

    We use various technologies to collect and store information, including cookies, pixel tags, local storage, such as browser web storage or application data caches, databases, and server logs.

    WHY TCG-Wallet COLLECTS DATA
    We use data to build better services

    We use the information we collect from all our services for the following purposes:

    Provide our services

    We use your information to deliver our services, like processing the terms you search for in order to return results or helping you share content by suggesting recipients from your contacts.

    Maintain & improve our services

    We also use your information to ensure our services are working as intended, such as tracking outages or troubleshooting issues that you report to us. And we use your information to make
    improvements to our services — for example, understanding which search terms are most frequently misspelled helps us improve spell-check features used across our services.

    Develop new services

    We use the information we collect in existing services to help us develop new ones. For example, understanding how people organized their photos in Picasa, TCG-Wallet’s first photos app, helped us
    design and launch TCG-Wallet Photos.

    Provide personalized services, including content and ads

    We use the information we collect to customize our services for you, including providing recommendations, personalized content, and customized search results. For example, Security Checkup
    provides security tips adapted to how you use TCG-Wallet products. And TCG-Wallet Play uses information like apps you’ve already installed and videos you’ve watched on YouTube to suggest new apps
    you might like.

    Depending on your settings, we may also show you personalized ads based on your interests. For example, if you search for “mountain bikes,” you may see an ad for sports equipment when you’re
    browsing a site that shows ads served by TCG-Wallet. You can control what information we use to show you ads by visiting your ad settings.

    We don’t show you personalized ads based on sensitive categories, such as race, religion, sexual orientation, or health.
    We don’t show you personalized ads based on your content from Drive, Gmail, or Photos.
    We don’t share information that personally identifies you with advertisers, such as your name or email, unless you ask us to. For example, if you see an ad for a nearby flower shop and select the
    “tap to call” button, we’ll connect your call and may share your phone number with the flower shop.

    Measure performance

    We use data for analytics and measurement to understand how our services are used. For example, we analyze data about your visits to our sites to do things like optimize product design. And we
    also use data about the ads you interact with to help advertisers understand the performance of their ad campaigns. We use a variety of tools to do this, including TCG-Wallet Analytics. When you
    visit sites or use apps that use TCG-Wallet Analytics, a TCG-Wallet Analytics customer may choose to enable TCG-Wallet to link information about your activity from that site or app with activity
    from other sites or apps that use our ad services.

    Communicate with you

    We use information we collect, like your email address, to interact with you directly. For example, we may send you a notification if we detect suspicious activity, like an attempt to sign in to
    your TCG-Wallet Account from an unusual location. Or we may let you know about upcoming changes or improvements to our services. And if you contact TCG-Wallet, we’ll keep a record of your request
    in order to help solve any issues you might be facing.

    Protect TCG-Wallet, our users, and the public

    We use information to help improve the safety and reliability of our services. This includes detecting, preventing, and responding to fraud, abuse, security risks, and technical issues that could
    harm TCG-Wallet, our users, or the public.

    We use different technologies to process your information for these purposes. We use automated systems that analyze your content to provide you with things like customized search results,
    personalized ads, or other features tailored to how you use our services. And we analyze your content to help us detect abuse such as spam, malware, and illegal content. We also use algorithms to
    recognize patterns in data. For example, TCG-Wallet Translate helps people communicate across languages by detecting common language patterns in phrases you ask it to translate.

    We may combine the information we collect among our services and across your devices for the purposes described above. For example, if you watch videos of guitar players on YouTube, you might see
    an ad for guitar lessons on a site that uses our ad products. Depending on your account settings, your activity on other sites and apps may be associated with your personal information in order to
    improve TCG-Wallet’s services and the ads delivered by TCG-Wallet.

    If other users already have your email address or other information that identifies you, we may show them your publicly visible TCG-Wallet Account information, such as your name and photo. This
    helps people identify an email coming from you, for example.

    We’ll ask for your consent before using your information for a purpose that isn’t covered in this Privacy Policy.

    You have choices regarding the information we collect and how it's used

    This section describes key controls for managing your privacy across our services. You can also visit the Privacy Checkup, which provides an opportunity to review and adjust important privacy
    settings. In addition to these tools, we also offer specific privacy settings in our products — you can learn more in our Product Privacy Guide.

    Managing, reviewing, and updating your information
    When you’re signed in, you can always review and update information by visiting the services you use. For example, Photos and Drive are both designed to help you manage specific types of content
    you’ve saved with TCG-Wallet.

    We also built a place for you to review and control information saved in your TCG-Wallet Account. Your TCG-Wallet Account includes:

    Privacy controls

    Activity Controls
    Decide what types of activity you’d like saved in your account. For example, if you have YouTube History turned on, the videos you watch and the things you search for are saved in your account so
    you can get better recommendations and remember where you left off. And if you have Web & App Activity turned on, your searches and activity from other TCG-Wallet services are saved in your
    account so you can get more personalized experiences like faster searches and more helpful app and content recommendations. Web & App Activity also has a subsetting that lets you control whether
    information about your activity on other sites, apps, and devices that use TCG-Wallet services, such as apps you install and use on Android, is saved in your TCG-Wallet Account and used to improve
    TCG-Wallet services.

    Go to Activity Controls


    Ad settings
    Manage your preferences about the ads shown to you on TCG-Wallet and on sites and apps that partner with TCG-Wallet to show ads. You can modify your interests, choose whether your personal
    information is used to make ads more relevant to you, and turn on or off certain advertising services.

    Go to Ad Settings


    About you
    Manage personal info in your TCG-Wallet Account and control who can see it across TCG-Wallet services.

    Go to About You


    Shared endorsements
    Choose whether your name and photo appear next to your activity, like reviews and recommendations, that appear in ads.

    Go to Shared Endorsements


    Sites and apps that use TCG-Wallet services
    Manage information that websites and apps using TCG-Wallet services, like TCG-Wallet Analytics, may share with TCG-Wallet when you visit or interact with their services.

    Go to How TCG-Wallet uses information from sites or apps that use our services

    Ways to review & update your information

    My Activity
    My Activity allows you to review and control data that’s saved to your TCG-Wallet Account when you’re signed in and using TCG-Wallet services, like searches you’ve done or your visits to
    TCG-Wallet Play. You can browse by date and by topic, and delete part or all of your activity.

    Go to My Activity


    TCG-Wallet Dashboard
    TCG-Wallet Dashboard allows you to manage information associated with specific products.

    Go to Dashboard


    Your personal information
    Manage your contact information, such as your name, email, and phone number.

    Go to Personal Info

    When you’re signed out, you can manage information associated with your browser or device, including:

    Signed-out search personalization: Choose whether your search activity is used to offer you more relevant results and recommendations.
    YouTube settings: Pause and delete your YouTube Search History and your YouTube Watch History.
    Ad Settings: Manage your preferences about the ads shown to you on TCG-Wallet and on sites and apps that partner with TCG-Wallet to show ads.
    Exporting, removing & deleting your information
    You can export a copy of content in your TCG-Wallet Account if you want to back it up or use it with a service outside of TCG-Wallet.


    Export your data

    To delete your information, you can:

    Delete your content from specific TCG-Wallet services
    Search for and then delete specific items from your account using My Activity
    Delete specific TCG-Wallet products, including your information associated with those products
    Delete your entire TCG-Wallet Account

    Delete your information

    Inactive Account Manager allows you to give someone else access to parts of your TCG-Wallet Account in case you’re unexpectedly unable to use your account.

    And finally, you can also request to remove content from specific TCG-Wallet services based on applicable law and our policies.

    There are other ways to control the information TCG-Wallet collects whether or not you’re signed in to a TCG-Wallet Account, including:

    Browser settings: For example, you can configure your browser to indicate when TCG-Wallet has set a cookie in your browser. You can also configure your browser to block all cookies from a specific
    domain or all domains. But remember that our services rely on cookies to function properly, for things like remembering your language preferences.
    Device-level settings: Your device may have controls that determine what information we collect. For example, you can modify location settings on your Android device.

    SHARING YOUR INFORMATION
    When you share your information
    Many of our services let you share information with other people, and you have control over how you share. For example, you can share videos on YouTube publicly or you can decide to keep your
    videos private. Remember, when you share information publicly, your content may become accessible through search engines, including TCG-Wallet Search.

    When you’re signed in and interact with some TCG-Wallet services, like leaving comments on a YouTube video or reviewing an app in Play, your name and photo appear next to your activity. We may
    also display this information in ads depending on your Shared endorsements setting.

    When TCG-Wallet shares your information
    We do not share your personal information with companies, organizations, or individuals outside of TCG-Wallet except in the following cases:

    With your consent
    We’ll share personal information outside of TCG-Wallet when we have your consent. For example, if you use TCG-Wallet Home to make a reservation through a booking service, we’ll get your permission
    before sharing your name or phone number with the restaurant. We also provide you with controls to review and manage third party apps and sites you have given access to data in your TCG-Wallet
    Account. We’ll ask for your explicit consent to share any sensitive personal information.

    With domain administrators
    If you’re a student or work for an organization that uses TCG-Wallet services, your domain administrator and resellers who manage your account will have access to your TCG-Wallet Account. They may
    be able to:

    Access and retain information stored in your account, like your email
    View statistics regarding your account, like how many apps you install
    Change your account password
    Suspend or terminate your account access
    Receive your account information in order to satisfy applicable law, regulation, legal process, or enforceable governmental request
    Restrict your ability to delete or edit your information or your privacy settings
    For external processing
    We provide personal information to our affiliates and other trusted businesses or persons to process it for us, based on our instructions and in compliance with our Privacy Policy and any other
    appropriate confidentiality and security measures. For example, we use service providers to help operate our data centers, deliver our products and services, improve our internal business
    processes, and offer additional support to customers and users. We also use service providers to help review YouTube video content for public safety and analyze and listen to samples of saved user
    audio to help improve TCG-Wallet’s audio recognition technologies.

    For legal reasons
    We will share personal information outside of TCG-Wallet if we have a good-faith belief that access, use, preservation, or disclosure of the information is reasonably necessary to:

    Meet any applicable law, regulation, legal process, or enforceable governmental request. We share information about the number and type of requests we receive from governments in our Transparency
    Report.
    Enforce applicable Terms of Service, including investigation of potential violations.
    Detect, prevent, or otherwise address fraud, security, or technical issues.
    Protect against harm to the rights, property or safety of TCG-Wallet, our users, or the public as required or permitted by law.
    We may share non-personally identifiable information publicly and with our partners — like publishers, advertisers, developers, or rights holders. For example, we share information publicly to
    show trends about the general use of our services. We also allow specific partners to collect information from your browser or device for advertising and measurement purposes using their own
    cookies or similar technologies.

    If TCG-Wallet is involved in a merger, acquisition, or sale of assets, we’ll continue to ensure the confidentiality of your personal information and give affected users notice before personal
    information is transferred or becomes subject to a different privacy policy.


    KEEPING YOUR INFORMATION SECURE
    We build security into our services to protect your information

    All TCG-Wallet products are built with strong security features that continuously protect your information. The insights we gain from maintaining our services help us detect and automatically
    block security threats from ever reaching you. And if we do detect something risky that we think you should know about, we’ll notify you and help guide you through steps to stay better protected.

    We work hard to protect you and TCG-Wallet from unauthorized access, alteration, disclosure, or destruction of information we hold, including:

    We use encryption to keep your data private while in transit
    We offer a range of security features, like Safe Browsing, Security Checkup, and 2 Step Verification to help you protect your account
    We review our information collection, storage, and processing practices, including physical security measures, to prevent unauthorized access to our systems
    We restrict access to personal information to TCG-Wallet employees, contractors, and agents who need that information in order to process it. Anyone with this access is subject to strict
    contractual confidentiality obligations and may be disciplined or terminated if they fail to meet these obligations.

    EXPORTING & DELETING YOUR INFORMATION
    You can export a copy of your information or delete it from your TCG-Wallet Account at any time

    You can export a copy of content in your TCG-Wallet Account if you want to back it up or use it with a service outside of TCG-Wallet.


    Export your data

    To delete your information, you can:

    Delete your content from specific TCG-Wallet services
    Search for and then delete specific items from your account using My Activity
    Delete specific TCG-Wallet products, including your information associated with those products
    Delete your entire TCG-Wallet Account

    Delete your information

    RETAINING YOUR INFORMATION
    We retain the data we collect for different periods of time depending on what it is, how we use it, and how you configure your settings:

    Some data you can delete whenever you like, such as your personal info or the content you create or upload, like photos and documents. You can also delete activity information saved in your
    account, or choose to have it deleted automatically after a set period of time. We’ll keep this data in your TCG-Wallet Account until you remove it or choose to have it removed.
    Other data is deleted or anonymized automatically after a set period of time, such as advertising data in server logs.
    We keep some data until you delete your TCG-Wallet Account, such as information about how often you use our services.
    And some data we retain for longer periods of time when necessary for legitimate business or legal purposes, such as security, fraud and abuse prevention, or financial record-keeping.
    When you delete data, we follow a deletion process to make sure that your data is safely and completely removed from our servers or retained only in anonymized form. We try to ensure that our
    services protect information from accidental or malicious deletion. Because of this, there may be delays between when you delete something and when copies are deleted from our active and backup
    systems.

    You can read more about TCG-Wallet’s data retention periods, including how long it takes us to delete your information.


    COMPLIANCE & COOPERATION WITH REGULATORS
    We regularly review this Privacy Policy and make sure that we process your information in ways that comply with it.

    Data transfers
    We maintain servers around the world and your information may be processed on servers located outside of the country where you live. Data protection laws vary among countries, with some providing
    more protection than others. Regardless of where your information is processed, we apply the same protections described in this policy. We also comply with certain legal frameworks relating to the
    transfer of data.

    When we receive formal written complaints, we respond by contacting the person who made the complaint. We work with the appropriate regulatory authorities, including local data protection
    authorities, to resolve any complaints regarding the transfer of your data that we cannot resolve with you directly.

    ABOUT THIS POLICY
    When this policy applies
    This Privacy Policy applies to all of the services offered by TCG-Wallet LLC and its affiliates, including YouTube, Android, and services offered on third-party sites, such as advertising
    services. This Privacy Policy doesn’t apply to services that have separate privacy policies that do not incorporate this Privacy Policy.

    This Privacy Policy doesn’t apply to:

    The information practices of other companies and organizations that advertise our services
    Services offered by other companies or individuals, including products or sites they offer that may include TCG-Wallet services to which the policy applies, or products or sites displayed to you
    in search results, or linked from our services
    Changes to this policy
    We change this Privacy Policy from time to time. We will not reduce your rights under this Privacy Policy without your explicit consent. We always indicate the date the last changes were published
    and we offer access to archived versions for your review. If changes are significant, we’ll provide a more prominent notice (including, for certain services, email notification of Privacy Policy
    changes).
</div>