<div id="app" class="app app-header-fixed app-sidebar-fixed app-content-full-height">

    <div id="header" class="app-header">

        <div class="navbar-header">
            <a href="#dashboard-1" class="navbar-brand">
                <img src="assets/img/ico/64.png" alt="Brand Image"/> <b class="me-3px"> ADAH </b>
            </a>
            <button type="button" class="navbar-mobile-toggler" data-toggle="app-sidebar-mobile">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>


        <div class="navbar-nav">
            <div class="navbar-item navbar-form">
                <form action method="POST" name="search">
                    <div class="form-group">
                        <label for="search">
                            <input id="search" type="text" class="form-control" placeholder="Buscar Voluntario"/>
                        </label>
                        <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
            <div class="navbar-item dropdown">
                <a href="#" data-bs-toggle="dropdown" class="navbar-link dropdown-toggle icon">
                    <i class="fa fa-bell"></i>
                    <span class="badge">5</span>
                </a>
                <div class="dropdown-menu media-list dropdown-menu-end">
                    <div class="dropdown-header">NOTIFICATIONS (5)</div>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <i class="fa fa-bug media-object bg-gray-500"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">Server Error Reports
                                <i class="fa fa-exclamation-circle text-danger"></i>
                            </h6>
                            <div class="text-muted fs-10px">3 minutes ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <img src="assets/img/user/user-1.jpg" class="media-object" alt/>
                            <i class="fab fa-facebook-messenger text-blue media-object-icon"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">John Smith</h6>
                            <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                            <div class="text-muted fs-10px">25 minutes ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <img src="assets/img/user/user-2.jpg" class="media-object" alt/>
                            <i class="fab fa-facebook-messenger text-blue media-object-icon"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading">Olivia</h6>
                            <p>Quisque pulvinar tellus sit amet sem scelerisque tincidunt.</p>
                            <div class="text-muted fs-10px">35 minutes ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <i class="fa fa-plus media-object bg-gray-500"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"> New User Registered</h6>
                            <div class="text-muted fs-10px">1 hour ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item media">
                        <div class="media-left">
                            <i class="fa fa-envelope media-object bg-gray-500"></i>
                            <i class="fab fa-google text-warning media-object-icon fs-14px"></i>
                        </div>
                        <div class="media-body">
                            <h6 class="media-heading"> New Email From John</h6>
                            <div class="text-muted fs-10px">2 hour ago</div>
                        </div>
                    </a>
                    <div class="dropdown-footer text-center">
                        <a href="#" class="text-decoration-none">View more</a>
                    </div>
                </div>
            </div>
            <div class="navbar-item navbar-user dropdown">
                <a href="#" class="navbar-link dropdown-toggle d-flex align-items-center" data-bs-toggle="dropdown">
                    <img src="assets/img/user/user-13.jpg" alt/>
                    <span>
                        <span class="d-none d-md-inline">Walter Nuñez</span>
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-end me-1">
                    <a href="#extra_profile" class="dropdown-item">Edit Profile</a>
                    <a href="#email_inbox" class="dropdown-item d-flex align-items-center">
                        Inbox
                        <span class="badge bg-danger rounded-pill ms-auto pb-4px">2</span>
                    </a>
                    <a href="#calendar" class="dropdown-item">Calendar</a>
                    <a href="#extra_settings_pagel" class="dropdown-item">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a href="#login" class="dropdown-item">Log Out</a>
                </div>
            </div>
        </div>

    </div>


    <div id="sidebar" class="app-sidebar" data-bs-theme="dark">

        <div class="app-sidebar-content" data-scrollbar="true" data-height="100%">

            <div class="menu">
                <div class="menu-profile">
                    <a href="#" class="menu-profile-link" data-toggle="app-sidebar-profile"
                       data-target="#appSidebarProfileMenu">
                        <div class="menu-profile-cover with-shadow"></div>
                        <div class="menu-profile-image">
                            <img src="assets/img/user/user-13.jpg" alt/>
                        </div>
                        <div class="menu-profile-info">
                            <div class="d-flex align-items-center">
                                <div class="flex-grow-1">Walter Nuñez</div>
                                <div class="menu-caret ms-auto"></div>
                            </div>
                            <small>Ing. Sistemas</small>
                        </div>
                    </a>
                </div>
                <div id="appSidebarProfileMenu" class="collapse">
                    <div class="menu-item pt-5px">
                        <a href="#" class="menu-link">
                            <div class="menu-icon"><i class="fa fa-cog"></i></div>
                            <div class="menu-text">Configurar Cuenta</div>
                        </a>
                    </div>
                    <div class="menu-item">
                        <a href="#" class="menu-link">
                            <div class="menu-icon"><i class="fa fa-pencil-alt"></i></div>
                            <div class="menu-text"> Enviar Reporte</div>
                        </a>
                    </div>
                    <div class="menu-item pb-5px">
                        <a href="#" class="menu-link">
                            <div class="menu-icon"><i class="fa fa-question-circle"></i></div>
                            <div class="menu-text"> Ayudas</div>
                        </a>
                    </div>
                    <div class="menu-divider m-0"></div>
                </div>
                <div class="menu-header">Menu</div>
                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Mantenimiento</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Mantenimiento 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Mantenimiento 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Mantenimiento 3</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Procesos</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item ">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Procesos 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Procesos 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Procesos 3</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Aprobaciones</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item active">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Aprobación 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Aprobación 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Aprobación 3</div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="menu-item has-sub">
                    <a href="#" class="menu-link">
                        <div class="menu-icon">
                            <i class="fa fa-sitemap"></i></div>
                        <div class="menu-text">Reportes</div>
                        <div class="menu-caret"></div>
                    </a>
                    <div class="menu-submenu">
                        <div class="menu-item active">
                            <a href="#dashboard-1" class="menu-link">
                                <div class="menu-text">Reporte 1</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-2" class="menu-link">
                                <div class="menu-text">Reporte 2</div>
                            </a>
                        </div>
                        <div class="menu-item">
                            <a href="#dashboard-3" class="menu-link">
                                <div class="menu-text">Reporte 3</div>
                            </a>
                        </div>
                    </div>
                </div>


                <div class="menu-item d-flex">
                    <a href="#"
                       class="app-sidebar-minify-btn ms-auto d-flex align-items-center text-decoration-none"
                       data-toggle="app-sidebar-minify">
                        <i class="fa fa-angle-double-left"></i>
                    </a>
                </div>

            </div>

        </div>

    </div>

    <div class="app-sidebar-bg" data-bs-theme="dark"></div>

    <div class="app-sidebar-mobile-backdrop">
        <a href="#" data-dismiss="app-sidebar-mobile" class="stretched-link"></a>
    </div>


    <div id="content" class="app-content d-flex flex-column p-0">

        <div class="app-content-padding flex-grow-1 overflow-hidden" data-scrollbar="true" data-height="100%">

            <ol class="breadcrumb float-xl-end">
                <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
                <li class="breadcrumb-item active">Calendar</li>
            </ol>


            <h1 class="page-header">Calendar <small>header small text goes here...</small></h1>

            <hr>

            <div class="row">

                <div class="d-none d-lg-block" style="width: 215px">
                    <div id="external-events" class="fc-event-list">
                        <h5 class="mb-3">Draggable Events</h5>
                        <div class="fc-event" data-color="#00acac">
                            <div class="fc-event-text">Meeting with Client</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-success"></i></div>
                        </div>
                        <div class="fc-event" data-color="#348fe2">
                            <div class="fc-event-text">IOS App Development</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-blue"></i></div>
                        </div>
                        <div class="fc-event" data-color="#f59c1a">
                            <div class="fc-event-text">Group Discussion</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-warning"></i></div>
                        </div>
                        <div class="fc-event" data-color="#ff5b57">
                            <div class="fc-event-text">New System Briefing</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-danger"></i></div>
                        </div>
                        <div class="fc-event">
                            <div class="fc-event-text">Brainstorming</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-dark"></i></div>
                        </div>
                        <hr class="my-3">
                        <h5 class="mb-3">Other Events</h5>
                        <div class="fc-event" data-color="#b6c2c9">
                            <div class="fc-event-text">Other Event 1</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-gray-500"></i></div>
                        </div>
                        <div class="fc-event" data-color="#b6c2c9">
                            <div class="fc-event-text">Other Event 2</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-gray-500"></i></div>
                        </div>
                        <div class="fc-event" data-color="#b6c2c9">
                            <div class="fc-event-text">Other Event 3</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-gray-500"></i></div>
                        </div>
                        <div class="fc-event" data-color="#b6c2c9">
                            <div class="fc-event-text">Other Event 4</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-gray-500"></i></div>
                        </div>
                        <div class="fc-event" data-color="#b6c2c9">
                            <div class="fc-event-text">Other Event 5</div>
                            <div class="fc-event-icon"><i class="fas fa-circle fa-fw fs-9px text-gray-500"></i></div>
                        </div>
                    </div>
                </div>

                <div class="col-lg">

                    <div id="calendar" class="calendar"></div>

                </div>
            </div>

        </div>

        <div id="footer" class="app-footer m-0">
            &copy; 2024 Icaros Net | Last Hammer Framework | ADAH - All Rights Reserved
            <span class="pull-right">
                <a href="#" class="btn-scroll-to-top" data-click="scroll-top">
                    <i class="fa fa-arrow-up"></i> <span class="hidden-xs">Back to Top</span>
                </a>
            </span>
        </div>

    </div>


    {{app_setting}}


    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top fixed-footer" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>

</div>