<div class="container m-auto" style="max-width: 800px">
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-2">
        <div class="col">
            <div class="card h-100">

                <i class="card-img-top fa-solid fa-location-dot fa-5x mt-3"></i>

                <div class="card-body">
                    <h5 class="card-title text-center">Location</h5>
                    <p class="card-text mt-5">Republica de Panama.<br>
                        Panama Oeste.<br>
                        Chorrera - Costa Verde<br>
                        Local 1100.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 12/12/2022</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <i class="card-img-top fa-solid fa-envelope fa-5x mt-3"></i>
                <div class="card-body">
                    <h5 class="card-title text-center">e-Mail</h5>
                    <p class="card-text mt-5">tcg.wallet.s@gmail.com.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 12/12/2022</small>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <i class="card-img-top fa-solid fa-phone fa-5x mt-3"></i>
                <div class="card-body">
                    <h5 class="card-title text-center">Whatsapp</h5>
                    <p class="card-text mt-5"><a class="text-decoration-none" href="https://wa.me/+50763146497" target="_blank">+507 6314-6497</a></p>

                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 12/12/2022</small>
                </div>
            </div>
        </div>
    </div>
    <div class="row d-grid gap-2 col-8 mx-auto mt-2 mb-2">
        <a href="/home" class="btn btn-success btn-lg fw-bold">Return to Home</a>
    </div>
</div>