<div id="app" class="app app-header-fixed app-sidebar-fixed app-content-full-height">
    <div id="header" class="app-header">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">
                <img src="assets/img/ico/64.png" alt="Brand Image"/>
                <b class="me-3px"> Last Hammer </b> Framework
            </a>
        </div>
        <div class="navbar-nav">
            <div class="navbar-item me-3">
                <a href="#modal-error-view" class="navbar-link d-flex align-items-center me-3 fs-3"
                   data-bs-toggle="modal">
                    Error Viewer <i class="fa-solid fa-circle-exclamation fs-3 ms-2"></i>

                </a>
            </div>
        </div>


    </div>

    <div id="content" class="app-content d-flex flex-column p-0">

        <div class="app-content-padding flex-grow-1 overflow-hidden" data-scrollbar="true" data-height="100%"
             data-spy-scroll="slide1">

            <ol class="breadcrumb float-xl-end">
                <li class="breadcrumb-item">LH-2 System</li>
                <li class="breadcrumb-item active">Setup</li>
            </ol>

            <h1 class="page-header">Setup Form <small>pre-Configuration <i class="fa fa-circle-question"
                                                                           data-bs-toggle="tooltip"
                                                                           data-bs-placement="auto"
                                                                           data-bs-html="true"
                                                                           data-bs-title="Pre-confirmation is important, if you want to finish later you can do it from <b>url/Admin</b>"></i>
                </small></h1>

            <hr class="mb-4">

            <form method="post" action="/Setup">
                <div class="row">
                    <div style="width: 180px">

                        <nav class="navbar navbar-sticky d-none d-xl-block my-n4 text-end h-100 w-150px">
                            <nav class="nav" data-lh-pl="spy" data-spy-target="slide1">
                                <a class="nav-link active" href="#general" data-toggle="scroll-to">General</a>
                                <a class="nav-link" href="#session" data-toggle="scroll-to">Session</a>
                                <a class="nav-link" href="#email" data-toggle="scroll-to">Email</a>
                                <a class="nav-link" href="#ftp" data-toggle="scroll-to">FTP</a>
                                <a class="nav-link" href="#database" data-toggle="scroll-to">Database</a>
                                <a class="nav-link" href="#admin-settings" data-toggle="scroll-to">Save Setting</a>
                            </nav>
                        </nav>

                    </div>
                    <div class="col-xl-8" data-spy-content="slide1">

                        <div id="general" class="mb-4 pb-3">

                            <h4 class="d-flex align-items-center mb-2">
                            <span class="iconify fs-24px me-2 text-body text-opacity-75 my-n1"
                                  data-icon="line-md:account-small"></span> General
                                <input type="hidden" name="step-1" value="false">
                                <span id="step-1-text" class="ms-3 text-success hide"> Step #1 Complete!!!</span>
                            </h4>

                            <p>Application settings and owner.</p>

                            <div class="card">
                                <div class="list-group list-group-flush fw-bold">

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="company-name">Company Name</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="company-name" name="json-company-name"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a href="#modal-company-name" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="company-owner">Company Owner</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="company-owner" name="json-company-owner"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a href="#modal-company-owner" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="project-name">Project Name</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="project-name" name="json-project-name"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a href="#modal-project-name" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="license">License</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="license" name="json-license" class="form-control-plaintext"
                                                       type="text" value="FREE-FREE-FREE-FREE" readonly required/>
                                                <input name="json-chk-license" type="hidden" value=""/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a href="#modal-license" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="protocol">Protocol</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="protocol" name="json-protocol" class="form-control-plaintext"
                                                       type="text" value="Click on Edit" readonly required/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Detected</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="domain">Domain for access</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="domain" name="json-domain" class="form-control-plaintext"
                                                       type="text" value="Click on Edit" readonly required/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Detected</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="lang">Default language</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="lang" name="json-lang" class="form-control-plaintext"
                                                       type="text"
                                                       value="Click on Edit" readonly required/>
                                            </div>
                                        </div>
                                        <div class="flex-fill">
                                            <label for="m-lang">Multiple languages?</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <input id="m-lang" name="json-m-lang" class="form-control-plaintext"
                                                       type="text" value="Click on Edit" readonly/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a href="#modal-lang" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>
                                    </div>

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <label for="entry">Entry</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="entry" name="json-entry" class="form-control-plaintext"
                                                       type="text" value="Click on Edit" readonly required/>
                                            </div>
                                        </div>
                                        <div class="w-125px">
                                            <a href="#modal-entry-view" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                        <div id="session" class="mb-4 pb-3">

                            <h4 class="d-flex align-items-center mb-2 mt-3">
                            <span class="iconify fs-24px me-2 text-body text-opacity-75 my-n1"
                                  data-icon="svg-spinners:clock"></span>
                                Session
                                <input type="hidden" name="step-2" value="false">
                                <span id="step-2-text" class="ms-3 text-success hide"> Step #2 Complete!!!</span>
                            </h4>

                            <p>let's configure how the sessions will work.</p>

                            <div class="card">
                                <div class="list-group list-group-flush fw-bold">

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-name">Web Session Name</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="session-name" name="json-session-name"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly/>
                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Detected</a>
                                        </div>

                                    </div>

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-inactivity"> Evaluate Session Inactivity</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="session-inactivity" name="json-session-inactivity"
                                                       class="form-control-plaintext" type="text" value="True" readonly
                                                       required/>
                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Security</a>
                                        </div>

                                    </div>

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-lifetime-days">Session Life Time</label>
                                            <label for="session-lifetime-hours"></label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="session-lifetime-days" name="json-session-lifetime-days"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>
                                                <input id="session-lifetime-hours" name="json-session-lifetime-hours"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>
                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a href="#modal-session-life-time" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>

                                    </div>

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-activity-expire-days">Session Activity Expire</label>
                                            <label for="session-activity-expire-hours"></label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-body text-opacity-25 me-2"></i>
                                                <input id="session-activity-expire-days"
                                                       name="json-session-activity-expire-days"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>
                                                <input id="session-activity-expire-hours"
                                                       name="json-session-activity-expire-hours"
                                                       class="form-control-plaintext" type="text" value="Click on Edit"
                                                       readonly required/>


                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a href="#modal-session-activity-expire" data-bs-toggle="modal"
                                               class="btn btn-secondary w-125px"><i
                                                        class="fa-solid fa-pen-to-square"></i> Edit</a>
                                        </div>

                                    </div>

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-secure">Session Secure</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="session-secure" name="json-session-secure"
                                                       class="form-control-plaintext" type="text" value="True" readonly
                                                       required/>
                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Security</a>
                                        </div>

                                    </div>

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-http-only">Session HTTP Only</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="session-http-only" name="json-session-http-only"
                                                       class="form-control-plaintext" type="text" value="True" readonly
                                                       required/>
                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Security</a>
                                        </div>

                                    </div>

                                    <div class="list-group-item d-flex align-items-center">

                                        <div class="flex-fill">
                                            <label for="session-same-site">Session Same Site</label>
                                            <div class="text-body text-opacity-60 d-flex align-items-center">
                                                <i class="fa fa-circle fs-6px mt-1px fa-fw text-success me-2"></i>
                                                <input id="session-same-site" name="json-session-same-site"
                                                       class="form-control-plaintext" type="text" value="True" readonly
                                                       required/>
                                            </div>
                                        </div>

                                        <div class="w-125px">
                                            <a class="btn btn-link text-decoration-none w-125px text-success text-end disabled fw-bold"
                                               role="button" aria-disabled="true">Automatically Security</a>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>

                        <div id="email" class="mb-4 pb-3">

                            <h4 class="d-flex align-items-center mb-2 mt-3">
                            <span class="iconify fs-24px me-2 text-body text-opacity-75 my-n1"
                                  data-icon="line-md:email-twotone"></span> E-Mail
                                <input type="hidden" name="step-3" value="false">
                                <span id="step-3-text" class="ms-3 text-success hide"> Step #3 Complete!!!</span>
                                <a href="#modal-add-email" data-bs-toggle="modal"
                                   class="btn btn-primary btn-xs ms-auto ml-1"><i class="fa fa-cog"></i> Add</a>
                            </h4>

                            <p>Let's configure how the email client works.</p>

                            <div class="card">
                                <div class="list-group list-group-flush fw-bold" id="email-content">


                                </div>
                            </div>

                        </div>

                        <div id="ftp" class="mb-4 pb-3">

                            <h4 class="d-flex align-items-center mb-2 mt-3">
                            <span class="iconify fs-24px me-2 text-body text-opacity-75 my-n1"
                                  data-icon="arcticons:andftp"></span> FTP Interfaces
                                <input type="hidden" name="step-4" value="false">
                                <span id="step-4-text" class="ms-3 text-success hide"> Step #4 Complete!!!</span>
                                <a href="#modal-add-ftp" data-bs-toggle="modal"
                                   class="btn btn-primary btn-xs ms-auto ml-1"><i
                                            class="fa fa-cog"></i> Add</a>
                            </h4>

                            <p>Here you configure your ftp connections.</p>

                            <div class="card">
                                <div class="list-group list-group-flush fw-bold" id="ftp-content">

                                </div>
                            </div>

                        </div>

                        <div id="database" class="mb-4 pb-3">

                            <h4 class="d-flex align-items-center mb-2 mt-3">
                            <span class="iconify fs-24px me-2 text-body text-opacity-75 my-n1"
                                  data-icon="solar:database-line-duotone"></span> Database

                                <input type="hidden" name="step-5" value="false">
                                <span id="step-5-text" class="ms-3 text-success hide"> Step #5 Complete!!!</span>

                                <a href="#modal-add-database" data-bs-toggle="modal"
                                   class="btn btn-primary btn-xs ms-auto ml-1"><i class="fa fa-cog"></i> Add</a>

                            </h4>

                            <p>let's configure how the System would be connected to the database system.</p>

                            <div class="card">
                                <div class="list-group list-group-flush fw-bold" id="database-content">

                                </div>

                            </div>
                        </div>

                        <div id="admin-settings" class="mb-4 pb-3">

                            <h4 class="d-flex align-items-center mb-2 mt-3">
                            <span class="iconify fs-24px me-2 text-body text-opacity-75 my-n1"
                                  data-icon="solar:restart-bold-duotone"></span>
                                Control settings
                            </h4>

                            <p>Validate, Save or Reset all website setting to factory default setting.</p>

                            <div class="card">
                                <div class="list-group list-group-flush fw-bold">

                                    <div class="list-group-item d-flex align-items-center">
                                        <div class="flex-fill">
                                            <div>Save Settings</div>
                                            <div class="text-body text-opacity-60">
                                                This action will save all the current system setting.
                                            </div>
                                        </div>
                                        <div>
                                            <button type="button" name="event" value="save" class="btn btn-red w-125px">
                                                Save
                                            </button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>


                <div class="modal fade" id="modal-company-name">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit Company Name or Individual</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="mb-3">
                                    <label class="form-label" for="i-company-name">Set the Name</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input id="i-company-name" name="i-company-name"
                                                   class="form-control opacity-50"
                                                   placeholder="Company Inc. LTD. | John Doe" value="">
                                        </div>
                                    </div>
                                </div>
                                <div id="a-company-name" class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> The information provided does not have the minimum expected (8
                                    characters).
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b> It is important to define the name of the company or individual
                                    person that implements this system, since this information must generally appear in
                                    documents that you generate officially.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-company-name" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-company-owner">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit Company Owner or Individual</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="mb-3">
                                    <label class="form-label" for="i-company-owner">Set the Name</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input id="i-company-owner" name="i-company-owner"
                                                   class="form-control opacity-50"
                                                   placeholder="Company Inc. LTD. | John Doe" value="">
                                        </div>
                                    </div>
                                </div>
                                <div id="a-company-owner" class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> The information provided does not have the minimum expected (8
                                    characters).
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b> It is important to define the name of the company owner or
                                    individual person that implements this system, since this information must generally
                                    appear in documents that you generate officially.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-company-owner" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-project-name">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit the Project Name</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="mb-3">
                                    <label class="form-label" for="i-project-name">Set the Project Name</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input id="i-project-name" name="i-project-name"
                                                   class="form-control opacity-50"
                                                   placeholder="Last Hammer Framework" value="">
                                        </div>
                                    </div>
                                </div>
                                <div id="a-project-name" class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> The information provided does not have the minimum expected (4
                                    characters).
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b> Here we must define the project name for this system, since this
                                    information should generally appear in documents that you officially generate and in
                                    the title/description of the page/hml.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-project-name" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-license">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit License </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">

                                <div class="row align-items-center mb-3">
                                    <label class="form-label" for="i-license">Set the License Key for support
                                        service</label>
                                    <div class="col-12">

                                        <div class="input-group mb-10px">
                                            <input type="text" id="i-license" name="i-license" class="form-control"
                                                   placeholder="1234-ABCD-1234-ABCD" value="FREE-FREE-FREE-FREE"
                                                   readonly>
                                            <div class="input-group-text">
                                                <input name="chk-license" type="hidden"/>
                                                <label for="chk-license"></label>
                                                <input id="chk-license" name="chk-license" type="checkbox"
                                                       class="form-check-input" checked>
                                            </div>
                                            <span class="input-group-text">Check for Free</span>
                                        </div>
                                    </div>
                                </div>
                                <div id="a-license" class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> You licence data is wrong, validate entering correct and real data.
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b> You do not need a License, unless you directly require
                                    integration support or specialized training in implementations.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-license" type="button" class="btn btn-theme">Save This</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-lang">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit Language</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="mb-3">
                                    <label class="form-label" for="i-lang">Set the default Language</label>
                                    <div class="row align-items-center">
                                        <div class="col-7">
                                            <select class="form-select" name="i-lang" id="i-lang" data-lh-pl="select"
                                                    data-width="100%">
                                                <option value="en" selected>English (default)</option>
                                                <option value="es">Español</option>
                                                <option value="fr">Française</option>
                                                <option value="de">Deutsch</option>
                                                <option value="zh">中國人</option>
                                                <option value="hi">हिंदी</option>
                                            </select>
                                        </div>
                                        <div class="col-5">
                                            <div class="form-check form-switch">
                                                <input name="multi-language" type="hidden"/>
                                                <input class="form-check-input" id="multi-language"
                                                       name="multi-language"
                                                       type="checkbox" checked/>
                                                <label class="form-check-label" for="multi-language">Enable
                                                    multi-language</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b>
                                    <p> The default language of the platform is English. Please note that the system
                                        includes by default the dictionaries of the languages selected for the platform
                                        and the administration system. You must decide if you want to support multiple
                                        languages at this time. Also consider that you should implement the template and
                                        dictionary system to expand the capabilities of using multiple languages, as
                                        well as including new languages.</p>
                                    <p class="mb-0"> The default language of the platform will be used as a last resort,
                                        the priority in Language detection is as follows:<br>
                                        1. Language set by end user as default.<br>
                                        2. language detected on the end user's operating system.<br>
                                        3. language set by default on the platform.</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-lang" type="button" class="btn btn-theme">Save This</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-entry-view">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Edit Page/View for Users </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="mb-3">
                                    <label class="form-label" for="i-entry">Set the Default Page/View for Users</label>
                                    <div class="row align-items-center">
                                        <div class="col-7">
                                            <select class="form-select" id="i-entry" name="i-entry" data-lh-pl="select"
                                                    data-width="100%">
                                                <option value="User-Access" selected>Login (Default)</option>
                                                <option value="Dashboard">Dashboard</option>
                                                <option value="Store">Store</option>
                                                <option value="Home">Home</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b>
                                    <p> It is important to establish a home or entry page by placing one of these by
                                        default, it will make it easier for users to understand the main purpose of this
                                        application or site.</p>
                                    <p class="mb-0">Keep in mind that if you select Dashboard, Home or Store, you will
                                        need to develop its content unlike the other entry points.</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-entry" type="button" class="btn btn-theme">Save This</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-session-life-time">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Set Time for Session</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-session-lifetime-days">Days</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="number" id="i-session-lifetime-days"
                                                       name="i-session-lifetime-days"
                                                       class="form-control opacity-50" placeholder="30" value="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-session-lifetime-hours">Hours</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="number" id="i-session-lifetime-hours"
                                                       name="i-session-lifetime-hours"
                                                       class="form-control opacity-50" placeholder="24" value="">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id="a-session-lifetime" class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> The session fields cannot be empty, you must fill in at least 1 or
                                    have a minimum value of 1 hour.
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b> Now it's time to set the duration of the default session
                                    started, this is mainly for browser data in general. all values will be recalculated
                                    and converted to seconds. the minimum value is 1 hour, if you choose use days it
                                    will override hours.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-lifetime" type="button" class="btn btn-theme">Save This</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-session-activity-expire">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Set Time for Session</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-session-activity-expire-days">Days</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="number" id="i-session-activity-expire-days"
                                                       name="i-session-activity-expire-days"
                                                       class="form-control opacity-50"
                                                       placeholder="30" value="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-session-activity-expire-hours">Hours</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="number" id="i-session-activity-expire-hours"
                                                       name="i-session-activity-expire-hours"
                                                       class="form-control opacity-50"
                                                       placeholder="24" value="">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div id="a-session-activity-expire"
                                     class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> The session fields cannot be empty, you must fill in at least 1 or
                                    have a minimum value of 1 hour.
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body">
                                    <b>Please note:</b> Now it's time to set the duration of the default session
                                    activity, this is mainly for user data in general. all values will be recalculated
                                    and converted to seconds. the minimum value is 1 hour.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-save-activity-expire" type="button" class="btn btn-theme">Save This
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-add-email">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Add New E-Mail Client Sender</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-name">Name</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-mail-name" name="i-mail-name"
                                                       class="form-control opacity-50" placeholder="Google Sender"
                                                       value="Google Sender">
                                            </div>
                                            <div id="a-mail-name"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection name must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-host">Host</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-mail-host" name="i-mail-host"
                                                       class="form-control opacity-50" placeholder="smtp.gmail.com"
                                                       value="smtp.gmail.com">
                                            </div>
                                            <div id="a-mail-host"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The host connecting to the mail system is not correct.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-port">Port</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="number" id="i-mail-port" name="i-mail-port"
                                                       class="form-control opacity-50" placeholder="587" value="587">
                                            </div>
                                            <div id="a-mail-port"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> Please enter a connection to the correct email system.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-user">User</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-mail-user" name="i-mail-user"
                                                       class="form-control opacity-50" placeholder="fulanito_73"
                                                       value="fulanito_73">
                                            </div>
                                            <div id="a-mail-user"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> You must enter a username for the email system.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-password">Password</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="input-group">
                                                    <input type="password" id="i-mail-password"
                                                           name="i-mail-password" class="form-control opacity-50"
                                                           placeholder="************" value="*@1Qazxsw22">
                                                    <button type="button" class="btn btn-primary">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="a-mail-password"
                                                 class="col-11 alert alert-warning alert-dismissible fade hide m-2 blink">
                                                <b>Error:</b> This password does not meet the minimum requirements.<br>
                                                Must contain at least one of the following symbols: ".@*_"<br>
                                                Must contain at least one uppercase letter<br>
                                                Must contain at least one lowercase letter<br>
                                                Must contain at least one number<br>
                                                Must be at least 13 characters long<br>
                                                <button type="button" class="btn-close"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-re-password">Re-Password</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="input-group">
                                                    <input type="password" id="i-mail-re-password"
                                                           name="i-mail-re-password" class="form-control opacity-50"
                                                           placeholder="************" value="*@1Qazxsw22">
                                                    <button type="button" class="btn btn-primary">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="a-mail-re-password"
                                                 class="col-11 alert alert-warning alert-dismissible fade hide m-2 blink">
                                                <b>Error:</b> This password is not identical to the previous one.
                                                <button type="button" class="btn-close"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-default">Default (support e-mail)</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-mail-default"
                                                       name="i-mail-default" class="form-control opacity-50"
                                                       placeholder="support@host.com::Name"
                                                       value="icarosnet@gmail.com::wnunez">
                                            </div>
                                            <div id="a-mail-default"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> We recommend using a real email name for sending email by
                                                default.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-prefix">Prefix on Subject (default all
                                            e-mail)</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-mail-prefix"
                                                       name="i-mail-prefix" class="form-control opacity-50"
                                                       placeholder="[TEST]"
                                                       value="[TEST]">
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-mail-protocol">Select Protocol</label>
                                        <select class="form-select" name="i-mail-protocol" id="i-mail-protocol"
                                                data-lh-pl="select" data-width="100%">
                                            <option value="tls" selected>TLS</option>
                                            <option value="ssl">SSL</option>
                                        </select>
                                    </div>
                                    <div id="a-mail-protocol"
                                         class="col-6 alert alert-danger alert-dismissible hide mb-3">
                                        <b>Error:</b> It is vitally important to choose a protocol, make sure it is
                                        correct.
                                        <button type="button"
                                                class="btn btn-sm btn-close remove-shadow"></button>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-4">
                                        <div class="form-check form-switch">
                                            <input name="i-mail-auth" type="hidden"/>
                                            <input class="form-check-input" type="checkbox" id="i-mail-auth"
                                                   name="i-mail-auth" checked>
                                            <label class="form-check-label"
                                                   for="i-mail-auth">Authentication</label>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-check form-switch">
                                            <input name="i-mail-debug" type="hidden" value="false"/>
                                            <input class="form-check-input" type="checkbox" id="i-mail-debug"
                                                   name="i-mail-debug">
                                            <label class="form-check-label" for="i-mail-debug">Debug</label>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-check form-switch form-check-inline">
                                            <input name="i-mail-test" type="hidden" value="false"/>
                                            <input class="form-check-input" type="checkbox" id="i-mail-test"
                                                   name="i-mail-test">
                                            <label class="form-check-label" for="i-mail-test">Test</label>
                                        </div>
                                    </div>
                                </div>

                                <div class="alert bg-body">
                                    <b>Please note:</b>
                                    <p>Now it's time to configure our email sending system, here you can add a
                                        configuration and run tests.</p>
                                    <p>This is mainly for sending notifications or any use you want to give it within
                                        your development.</p>
                                    <p>Also keep in mind that some email platforms require a different configuration
                                        than this.</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-add-mail" type="button" class="btn btn-theme">Add This Sender</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-add-ftp">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Add FTP Connection</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">

                                <div class="row">


                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-name">Name</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-ftp-name"
                                                       name="i-ftp-name" class="form-control opacity-50"
                                                       placeholder="FTP Local"
                                                       value="FTP Local">
                                            </div>
                                            <div id="a-ftp-name"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection name must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-host">Host</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-ftp-host"
                                                       name="i-ftp-host" class="form-control opacity-50"
                                                       placeholder="127.0.0.1"
                                                       value="127.0.0.1">
                                            </div>
                                            <div id="a-ftp-host"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection Host must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-port">Port</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-ftp-port"
                                                       name="i-ftp-port" class="form-control opacity-50"
                                                       placeholder="21"
                                                       value="21">
                                            </div>
                                            <div id="a-ftp-port"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection Port must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-user">User</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-ftp-user"
                                                       name="i-ftp-user" class="form-control opacity-50"
                                                       placeholder="fulanito_73"
                                                       value="fulanito_73">
                                            </div>
                                            <div id="a-ftp-user"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection User must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>


                                </div>

                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-password">Password</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="input-group">
                                                    <input type="password" id="i-ftp-password"
                                                           name="i-ftp-password" class="form-control opacity-50"
                                                           placeholder="************" value="*@1Qazxsw22">
                                                    <button type="button" class="btn btn-primary">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="a-ftp-password"
                                                 class="col-11 alert alert-warning alert-dismissible fade hide m-2 blink">
                                                <b>Error:</b> This password does not meet the minimum requirements.<br>
                                                Must contain at least one of the following symbols: ".@*_"<br>
                                                Must contain at least one uppercase letter<br>
                                                Must contain at least one lowercase letter<br>
                                                Must contain at least one number<br>
                                                Must be at least 13 characters long<br>
                                                <button type="button" class="btn-close"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-re-password">Re-Password</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="input-group">
                                                    <input type="password" id="i-ftp-re-password"
                                                           name="i-ftp-re-password" class="form-control opacity-50"
                                                           placeholder="************" value="*@1Qazxsw22">
                                                    <button type="button" class="btn btn-primary">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="a-ftp-re-password"
                                                 class="col-11 alert alert-warning alert-dismissible fade hide m-2 blink">
                                                <b>Error:</b> This password is not identical to the previous one.
                                                <button type="button" class="btn-close"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="row">


                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-path">Default Path (On Server)</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-ftp-path"
                                                       name="i-ftp-path" class="form-control opacity-50"
                                                       placeholder="/path/dir"
                                                       value="/path/dir">
                                            </div>
                                            <div id="a-ftp-path"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> add the default path to the system example "/".
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-ftp-path">Connection mode</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-check form-switch">
                                                    <input name="i-ftp-mode" type="hidden"/>
                                                    <input class="form-check-input" type="checkbox" id="i-ftp-mode"
                                                           name="i-ftp-mode" checked>
                                                    <label class="form-check-label" for="i-ftp-mode">Enable Passive
                                                        Mode</label>
                                                </div>
                                            </div>
                                            <div id="a-ftp-mode"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> If you want you can add the connection mode.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="alert bg-body">
                                    <b>Please note:</b>
                                    <p>Now it is time to configure our FTP connection system. We recommend having an
                                        internal local system, as well as external configurations to other systems.</p>
                                    <p>This is mainly for interconnection between systems through ftp consumption.</p>
                                    <p>Also note that some platforms offer consumer APIs that require a different setup
                                        than this one and are based on a different technology.</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                <button name="b-add-ftp" type="button" class="btn btn-theme">Add This FTP Connection
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-add-database">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Setup Database Credential</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="row">


                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-database-name">DB Name</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-database-name"
                                                       name="i-database-name" class="form-control opacity-50"
                                                       placeholder="DB Mirror"
                                                       value="DB Mirror">
                                            </div>
                                            <div id="a-database-name"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection name must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-database-host">DB Host</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-database-host"
                                                       name="i-database-host" class="form-control opacity-50"
                                                       placeholder="127.0.0.1"
                                                       value="127.0.0.1">
                                            </div>
                                            <div id="a-database-host"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> The connection Host must not be empty.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-database-user">DB User</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-database-user"
                                                       name="i-database-user" class="form-control opacity-50"
                                                       placeholder="fulanito_73"
                                                       value="fulanito_73">
                                            </div>
                                            <div id="a-database-user"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> you need to set a User to get connected to the database.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-database-port">Port</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" id="i-database-port"
                                                       name="i-database-port" class="form-control opacity-50"
                                                       placeholder="3306"
                                                       value="3306">
                                            </div>
                                            <div id="a-database-port"
                                                 class="col-12 alert alert-danger alert-dismissible hide mb-3">
                                                <b>Error:</b> you need to set a Port to get connected to the database.
                                                <button type="button"
                                                        class="btn btn-sm btn-close remove-shadow"></button>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-database-password">Password</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="input-group">
                                                    <input type="password" id="i-database-password"
                                                           name="i-database-password" class="form-control opacity-50"
                                                           placeholder="************" value="*@1Qazxsw22">
                                                    <button type="button" class="btn btn-primary">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="a-database-password"
                                                 class="col-11 alert alert-warning alert-dismissible fade hide m-2 blink">
                                                <b>Error:</b> This password does not meet the minimum requirements.<br>
                                                Must contain at least one of the following symbols: ".@*_"<br>
                                                Must contain at least one uppercase letter<br>
                                                Must contain at least one lowercase letter<br>
                                                Must contain at least one number<br>
                                                Must be at least 13 characters long<br>
                                                <button type="button" class="btn-close"></button>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-6 mb-3">
                                        <label class="form-label" for="i-database-re-password">Re-Password</label>
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="input-group">
                                                    <input type="password" id="i-database-re-password"
                                                           name="i-database-re-password" class="form-control opacity-50"
                                                           placeholder="************" value="*@1Qazxsw22">
                                                    <button type="button" class="btn btn-primary">
                                                        <i class="fa-solid fa-eye"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <div id="a-database-re-password"
                                                 class="col-11 alert alert-warning alert-dismissible fade hide m-2 blink">
                                                <b>Error:</b> This password is not identical to the previous one.
                                                <button type="button" class="btn-close"></button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-6 d-grid gap-2 d-block">
                                        <button type="button" name="test-database-connection"
                                                class="btn btn-primary mb-2">
                                            Test Database Connection
                                        </button>
                                        <input type="hidden" name="test-database-connection-result" value="false">
                                    </div>
                                    <div class="col-6">
                                        <div id="a-database-con-connection-error"
                                             class="alert alert-danger alert-dismissible hide mb-3">
                                            <b>Error!!!</b>
                                            <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                        </div>
                                        <div id="a-database-con-connection-success"
                                             class="alert alert-success alert-dismissible hide mb-3">
                                            <b>Success!!!</b>
                                            <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                        </div>
                                    </div>
                                </div>
                                <div id="a-database-con-config" class="alert alert-danger alert-dismissible hide mb-3">
                                    <b>Error:</b> The session fields cannot be empty, you must fill in at least 1 or
                                    have a minimum value of 1 hour.
                                    <button type="button" class="btn btn-sm btn-close remove-shadow"></button>
                                </div>
                                <div class="alert bg-body mt-3">
                                    <b>Please note:</b> In this section we are going to configure our connection to our
                                    database so that the system can establish the minimum structures necessary for its
                                    configuration.<br><br>
                                    Keep in mind that the password field has minimum requirements:<br>
                                    - Use 8 or more characters.<br>
                                    - with a mix of letters, numbers & symbols.
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
                                <button name="b-add-database" type="button" class="btn btn-theme">Add This Database
                                    Connection
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-error-view">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Error Viewer</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-3">
                                            <button type="button" id="reload-btn"
                                                    class="btn btn-outline-primary d-block">Reload Error
                                            </button>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <iframe id="error-viewer" class="w-100 vh-80"></iframe>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="modal fade" id="welcome">
                    <div class="modal-dialog modal-lg modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Welcome to Last Hammer Framework</h5>
                            </div>
                            <div class="modal-body">
                                <p>A typical dashboard framework provides a set of tools and components to build
                                    web-based dashboards. These frameworks often focus on the following key areas:</p>
                                <ul class="pe-15px">
                                    <li><strong>Pre-built UI Components:</strong> Ready-to-use elements like charts,
                                        graphs, tables, widgets, and navigation menus to display data visually. These
                                        components are responsive and customizable.
                                    </li>
                                    <li><strong>Data Integration:</strong> Easy integration with various data sources
                                        (e.g., APIs, databases, CSV files) and supports dynamic data binding to update
                                        the dashboard in real-time.
                                    </li>
                                    <li><strong>Layouts and Templates:</strong> Customizable layout templates for
                                        arranging components and content in a structured way, often with a grid system
                                        or drag-and-drop functionality.
                                    </li>
                                    <li><strong>Theming and Customization:</strong> Options to apply different themes
                                        and styles to match the branding of your application, allowing for visual
                                        consistency and personalization.
                                    </li>
                                    <li><strong>Interactivity:</strong> Supports interactive elements like filters,
                                        search bars, drill-downs, and user input forms to make the dashboard more
                                        engaging and user-friendly.
                                    </li>
                                    <li><strong>Authentication and Access Control:</strong> Implements user
                                        authentication and role-based access controls to manage who can view or modify
                                        specific sections of the dashboard.
                                    </li>
                                    <li><strong>Backend Integration:</strong> Includes server-side integration, allowing
                                        you to connect to databases, handle user sessions, and process data securely.
                                    </li>
                                    <li><strong>Responsive Design:</strong> Ensures that the dashboard is accessible and
                                        functional across different devices and screen sizes, including mobile devices.
                                    </li>
                                    <li><strong>Performance Optimization:</strong> Features like lazy loading, data
                                        caching, and efficient rendering techniques to make the dashboard smooth and
                                        fast.
                                    </li>
                                    <li><strong>Plugins and Extensions:</strong> Many frameworks offer plugin
                                        architectures or third-party integrations, allowing you to extend the
                                        functionality of the dashboard with additional tools like data visualization
                                        libraries (e.g., D3.js, Chart.js).
                                    </li>
                                </ul>
                                <p>Overall, a dashboard framework simplifies the process of building complex,
                                    data-driven applications by providing pre-built components, integrations, and
                                    customization options.</p>
                                <div class="container">
                                    <div class="row align-items-end">
                                        <div class="d-grid gap-2 col-6 mx-auto">
                                            <button type="button" id="play"
                                                    class="btn btn-outline-indigo btn-lg d-block"
                                                    data-bs-dismiss="modal">Continue
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </form>

        </div>
        <div id="footer" class="app-footer m-0">
            &copy; 2024 Icaros Net | Last Hammer Framework - All Rights Reserved
            <span class="pull-right">
                <a href="#" class="btn-scroll-to-top" data-click="scroll-top">
                    <i class="fa fa-arrow-up"></i> <span class="hidden-xs">Back to Top</span>
                </a>
            </span>
        </div>

    </div>

    <a href="#" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>